<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>締日条件マスター | 販売管理</title>
  <style>
    :root{font-family:Inter,"Noto Sans JP",system-ui,sans-serif;color:#172033;background:#f5f7fb;font-size:13px}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0}h1,h2,h3,p{margin:0}
    header{height:52px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;border-bottom:1px solid #dce4ee;background:#fff}header h1{font-size:15px;font-weight:800;letter-spacing:0}main{padding:12px 18px 40px}.layout{display:grid;grid-template-columns:390px minmax(0,1fr);gap:12px;align-items:start}.card{min-width:0;border:1px solid #dce4ee;border-radius:6px;background:#fff;overflow:hidden}.head{display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:48px;padding:9px 12px;border-bottom:1px solid #e7edf4}.head h2{font-size:14px}.actions{display:flex;align-items:center;gap:7px}.muted{color:#64748b;font-size:11px;line-height:1.5}
    button,input,select,textarea{font:inherit;color:#172033}button{min-height:30px;padding:5px 9px;border:1px solid #cad6e6;border-radius:4px;background:#fff;cursor:pointer}button:hover{border-color:#8ebcff}button:disabled{opacity:.45;cursor:not-allowed}.primary{background:#0b6ff6;color:#fff;border-color:#0b6ff6;font-weight:800}.secondary{color:#075ecf;border-color:#a9caff}label{display:grid;gap:4px;color:#475569;font-size:10px;font-weight:700}input,select,textarea{width:100%;min-height:32px;padding:5px 8px;border:1px solid #ced8e5;border-radius:4px;background:#fff}textarea{min-height:82px;resize:vertical}input:disabled,select:disabled,textarea:disabled{background:#f3f6fa;color:#64748b}
    .filters{display:flex;align-items:end;gap:8px;padding:10px 12px;border-bottom:1px solid #e7edf4}.filters label{flex:1}.cycle-table{width:100%;border-collapse:collapse;table-layout:fixed}.cycle-table th,.cycle-table td{padding:9px 8px;border-bottom:1px solid #edf1f6;text-align:left;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.cycle-table th{background:#f8faff;color:#64748b;font-size:10px}.cycle-table th:nth-child(2),.cycle-table td:nth-child(2){width:108px}.cycle-table th:last-child,.cycle-table td:last-child{width:54px}.cycle-table tbody tr{cursor:pointer}.cycle-table tbody tr:hover{background:#e7f0ff}.cycle-table tbody tr.selected{background:#d9e9ff;box-shadow:inset 3px 0 #0b6ff6}.status{display:inline-block;padding:2px 5px;border-radius:3px;background:#e7f7ed;color:#137333;font-size:10px;font-weight:800}.status.inactive{background:#eef1f5;color:#64748b}.empty{padding:30px 12px;text-align:center;color:#64748b}
    .detail-toolbar{display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:1px solid #e7edf4}.detail-toolbar .message{margin-right:auto}.panel{padding:14px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.full{grid-column:1/-1}.check{display:flex;align-items:center;gap:7px;min-height:32px;color:#334155;font-size:11px}.check input{width:auto;min-height:auto}.calculation{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;padding:12px;border:1px solid #dce4ee;border-radius:5px;background:#f8fafc}.calculation h3{grid-column:1/-1;font-size:12px}.lock{grid-column:1/-1;padding:8px 10px;border-left:3px solid #d89b00;background:#fff8e1;color:#7a4b00;font-size:11px}.stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid #e2e8f0;border-radius:5px;overflow:hidden}.stat{padding:10px;border-right:1px solid #e2e8f0}.stat:last-child{border-right:0}.stat strong{display:block;margin-top:3px;font-size:16px}.history{width:100%;border-collapse:collapse;margin-top:14px}.history th,.history td{padding:8px;border-bottom:1px solid #edf1f6;text-align:left;font-size:11px}.history th{background:#f8faff;color:#64748b;font-size:10px}.form-actions{display:flex;align-items:end;justify-content:flex-end;gap:8px;margin-top:14px;padding-top:12px;border-top:1px solid #edf1f6}.form-actions .message{margin-right:auto}.reason{width:min(360px,48%)}.message.error{color:#b42318}
    @media(max-width:1120px){.layout{grid-template-columns:1fr}.list-card{max-height:470px;overflow:auto}}@media(max-width:680px){main{padding:8px}.form-grid,.calculation{grid-template-columns:1fr}.calculation h3,.lock,.full{grid-column:auto}.stats{grid-template-columns:repeat(2,1fr)}.stat{border-bottom:1px solid #e2e8f0}.form-actions{align-items:stretch;flex-wrap:wrap}.reason{width:100%}}
  </style>
</head>
<body>
  <header><h1>締日条件マスター</h1><div class="actions"><span class="muted">{{ $user->name }}</span><form method="post" action="{{ route('logout') }}">@csrf<button type="submit">ログアウト</button></form></div></header>
  <main>
    <div class="layout">
      <section class="card list-card">
        <div class="head"><div><h2>締日・入金条件</h2><p id="result-count" class="muted"></p></div>@if($canEdit)<button id="new-cycle" class="secondary" type="button">新規登録</button>@endif</div>
        <form id="filters" class="filters"><label>状態<select id="filter-active"><option value="all">すべて</option><option value="active">有効</option><option value="inactive">休止</option></select></label><button class="primary" type="submit">表示</button></form>
        <table class="cycle-table"><thead><tr><th>条件名</th><th>締日</th><th>状態</th></tr></thead><tbody id="cycle-list"></tbody></table>
        <div id="empty-list" class="empty" hidden>条件はありません。</div>
      </section>

      <section class="card">
        <div class="head"><div><h2 id="detail-title">条件を選択</h2><p id="detail-subtitle" class="muted">一覧から締日条件を選択してください。</p></div><div class="actions">@if($canEdit)<button id="copy-cycle" type="button" hidden>複製して新規</button>@endif<button id="reload-cycle" type="button" disabled>再読込</button></div></div>
        <div class="detail-toolbar"><span id="detail-message" class="message muted"></span></div>
        <div id="detail-empty" class="empty">締日、入金月、入金日を条件として管理します。</div>
        <form id="cycle-form" class="panel" hidden>
          @csrf
          <div class="form-grid">
            <label class="full">条件名<input id="name" maxlength="120" required></label>
            <div class="calculation full">
              <h3>請求・入金計算</h3>
              <div id="lock-notice" class="lock" hidden>すでに取引で使用されているため、計算条件は変更できません。変更する場合は「複製して新規」を使用します。</div>
              <label>請求方式<select id="billing-method"><option value="monthly_closing">月次締め</option><option value="per_shipment">都度請求</option><option value="cash_immediate">現金即時</option></select></label>
              <label id="closing-day-label">締日<select id="closing-day"></select></label>
              <span></span>
              <label id="payment-offset-label">入金月<select id="payment-offset">@for($i=0;$i<=12;$i++)<option value="{{ $i }}">{{ $i === 0 ? '当月' : ($i === 1 ? '翌月' : $i.'か月後') }}</option>@endfor</select></label>
              <label id="payment-day-label">入金日<select id="payment-day"></select></label>
            </div>
            <label class="full">説明・運用メモ<textarea id="description" maxlength="2000"></textarea></label>
            <label class="check full"><input id="is-active" type="checkbox">有効な条件として使用する</label>
            <div class="stats full"><div class="stat"><span class="muted">取引先</span><strong id="count-customers">0</strong></div><div class="stat"><span class="muted">受注</span><strong id="count-orders">0</strong></div><div class="stat"><span class="muted">出荷</span><strong id="count-shipments">0</strong></div><div class="stat"><span class="muted">請求</span><strong id="count-invoices">0</strong></div></div>
            <div class="full"><h3 style="font-size:12px;margin:3px 0 6px">最近の変更</h3><table class="history"><thead><tr><th>日時</th><th>担当者</th><th>内容</th><th>理由</th></tr></thead><tbody id="history-list"></tbody></table><div id="history-empty" class="empty">この画面での変更履歴はまだありません。</div></div>
          </div>
          <div class="form-actions"><span id="form-message" class="message muted"></span><label id="reason-label" class="reason">変更理由<input id="change-reason" maxlength="1000" placeholder="例：入金条件の見直し"></label>@if($canEdit)<button class="primary" type="submit">保存</button>@endif</div>
        </form>
      </section>
    </div>
  </main>
  <script>
    const canEdit=@json($canEdit),state={selectedId:null,selected:null,isNew:false,dirty:false};
    const el=id=>document.getElementById(id),labels={name:'条件名',billing_method:'請求方式',closing_day:'締日',payment_month_offset:'入金月',payment_day:'入金日',change_reason:'変更理由'};
    function addDayOptions(select,allowEmpty=false){select.innerHTML=allowEmpty?'<option value="">指定なし</option>':'';for(let day=1;day<=30;day++){const option=document.createElement('option');option.value=day;option.textContent=`${day}日`;select.appendChild(option)}const end=document.createElement('option');end.value='31';end.textContent='月末';select.appendChild(end)}
    addDayOptions(el('closing-day'));addDayOptions(el('payment-day'),true);
    const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('input[name="_token"]')?.value||''},...options});const data=await response.json().catch(()=>({}));if(!response.ok){const errors=data.errors?Object.entries(data.errors).map(([key,value])=>`${labels[key]||key}: ${value[0]}`).join(' / '):null;throw new Error(errors||data.message||'処理に失敗しました。')}return data.data};
    const dayLabel=value=>value==null?'-':Number(value)===31?'月末':`${value}日`;
    const methodLabel=value=>({monthly_closing:'月次締め',per_shipment:'都度請求',cash_immediate:'現金即時'}[value]||value);
    const confirmDiscard=()=>!state.dirty||confirm('保存していない変更があります。破棄してよいですか？');
    function message(node,text,error=false){node.textContent=text;node.classList.toggle('error',error)}
    async function loadList(){try{const data=await api(`/api/v1/masters/billing-cycles?active=${el('filter-active').value}`);renderList(data.billing_cycles)}catch(error){message(el('detail-message'),error.message,true)}}
    function renderList(items){const body=el('cycle-list');body.innerHTML='';items.forEach(item=>{const row=document.createElement('tr');row.classList.toggle('selected',String(item.id)===String(state.selectedId));const name=document.createElement('td');name.innerHTML='<strong></strong><div class="muted"></div>';name.querySelector('strong').textContent=item.name;name.querySelector('.muted').textContent=methodLabel(item.billing_method);const closing=document.createElement('td');closing.textContent=item.billing_method==='monthly_closing'?dayLabel(item.closing_day):methodLabel(item.billing_method);const status=document.createElement('td');const badge=document.createElement('span');badge.className=`status${item.is_active?'':' inactive'}`;badge.textContent=item.is_active?'有効':'休止';status.appendChild(badge);row.append(name,closing,status);row.onclick=()=>selectCycle(item.id);body.appendChild(row)});el('empty-list').hidden=items.length>0;el('result-count').textContent=`${items.length}件`}
    async function selectCycle(id){if(String(id)===String(state.selectedId)&&!state.isNew)return;if(!confirmDiscard())return;state.selectedId=id;state.isNew=false;await loadCycle(id);await loadList()}
    async function loadCycle(id){message(el('detail-message'),'読み込み中です。');try{const data=await api(`/api/v1/masters/billing-cycles/${id}`);state.selected=data.billing_cycle;fillForm(data.billing_cycle);showForm();message(el('detail-message'),'')}catch(error){message(el('detail-message'),error.message,true)}}
    function fillForm(c){el('name').value=c.name;el('billing-method').value=c.billing_method;el('closing-day').value=String(c.closing_day??31);el('payment-offset').value=String(c.payment_month_offset??1);el('payment-day').value=c.payment_day==null?'':String(c.payment_day);el('description').value=c.description||'';el('is-active').checked=!!c.is_active;el('change-reason').value='';el('detail-title').textContent=c.name;el('detail-subtitle').textContent=`${methodLabel(c.billing_method)} / ${c.billing_method==='monthly_closing'?dayLabel(c.closing_day):'-'} / ${paymentText(c)}`;renderUsage(c.usage_counts||{});renderHistory(c.history||[]);el('lock-notice').hidden=!c.is_calculation_locked;el('copy-cycle').hidden=!canEdit;el('reason-label').hidden=!canEdit;applyMethodState(c.is_calculation_locked);state.dirty=false}
    function paymentText(c){if(c.billing_method==='cash_immediate')return'現金即時';const month=Number(c.payment_month_offset)===0?'当月':Number(c.payment_month_offset)===1?'翌月':`${c.payment_month_offset}か月後`;return `${month}${dayLabel(c.payment_day)}`}
    function showForm(){el('detail-empty').hidden=true;el('cycle-form').hidden=false;el('reload-cycle').disabled=false}
    function newCycle(source=null){if(!confirmDiscard())return;state.selectedId=null;state.selected=null;state.isNew=true;el('cycle-form').reset();el('name').value=source?`${source.name}（新規）`:'';el('billing-method').value=source?.billing_method||'monthly_closing';el('closing-day').value=String(source?.closing_day??31);el('payment-offset').value=String(source?.payment_month_offset??1);el('payment-day').value=source?.payment_day==null?'31':String(source.payment_day);el('description').value=source?.description||'';el('is-active').checked=true;el('detail-title').textContent=source?'条件を複製して新規登録':'新しい締日条件';el('detail-subtitle').textContent='計算条件を入力して保存します。';el('lock-notice').hidden=true;el('copy-cycle').hidden=true;el('reason-label').hidden=true;renderUsage({});renderHistory([]);showForm();applyMethodState(false);state.dirty=false;el('name').focus()}
    function applyMethodState(locked=state.selected?.is_calculation_locked&&!state.isNew){const method=el('billing-method').value,isCash=method==='cash_immediate',isMonthly=method==='monthly_closing';el('closing-day-label').hidden=!isMonthly;el('payment-offset-label').hidden=isCash;el('payment-day-label').hidden=isCash;['billing-method','closing-day','payment-offset','payment-day'].forEach(id=>el(id).disabled=!canEdit||locked);['name','description','is-active','change-reason'].forEach(id=>el(id).disabled=!canEdit)}
    function renderUsage(c){el('count-customers').textContent=(c.customers||0).toLocaleString();el('count-orders').textContent=(c.sales_orders||0).toLocaleString();el('count-shipments').textContent=(c.shipments||0).toLocaleString();el('count-invoices').textContent=(c.invoices||0).toLocaleString()}
    function renderHistory(items){const body=el('history-list');body.innerHTML='';items.forEach(item=>{const row=document.createElement('tr');[item.occurred_at?new Date(item.occurred_at).toLocaleString('ja-JP'):'-',item.user_name||'-',item.event||'-',item.reason||'-'].forEach(text=>{const cell=document.createElement('td');cell.textContent=text;row.appendChild(cell)});body.appendChild(row)});el('history-empty').hidden=items.length>0}
    function payload(){const method=el('billing-method').value;return{name:el('name').value.trim(),billing_method:method,closing_day:method==='monthly_closing'?Number(el('closing-day').value):null,payment_month_offset:method==='cash_immediate'?0:Number(el('payment-offset').value),payment_day:method==='cash_immediate'||!el('payment-day').value?null:Number(el('payment-day').value),description:el('description').value.trim()||null,is_active:el('is-active').checked,change_reason:el('change-reason').value.trim()||null}}
    async function save(event){event.preventDefault();if(!canEdit)return;const body=payload();if(!state.isNew&&!body.change_reason){message(el('form-message'),'変更理由を入力してください。',true);return}message(el('form-message'),'保存中です。');try{const data=await api(state.isNew?'/api/v1/masters/billing-cycles':`/api/v1/masters/billing-cycles/${state.selectedId}`,{method:state.isNew?'POST':'PUT',body:JSON.stringify(body)});state.selectedId=data.billing_cycle.id;state.isNew=false;state.dirty=false;await loadCycle(state.selectedId);await loadList();message(el('form-message'),'保存しました。')}catch(error){message(el('form-message'),error.message,true)}}
    el('filters').onsubmit=event=>{event.preventDefault();loadList()};el('new-cycle')?.addEventListener('click',()=>newCycle());el('copy-cycle')?.addEventListener('click',()=>newCycle(state.selected));el('reload-cycle').onclick=()=>state.selectedId&&loadCycle(state.selectedId);el('billing-method').onchange=()=>applyMethodState(false);el('cycle-form').onsubmit=save;el('cycle-form').addEventListener('input',()=>state.dirty=true);el('cycle-form').addEventListener('change',()=>state.dirty=true);window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue=''}});loadList();
  </script>
</body>
</html>
