<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
  <title>商品マスター | 販売管理</title>
  <style>
    :root{font-family:Inter,"Noto Sans JP",system-ui,sans-serif;color:#172033;background:#f5f7fb;font-size:13px}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0}h1,h2,h3,p{margin:0}header{height:52px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;border-bottom:1px solid #dce4ee;background:#fff}header h1{font-size:15px;font-weight:800;letter-spacing:0}main{padding:12px 18px 40px}.layout{display:grid;grid-template-columns:410px minmax(0,1fr);gap:12px;align-items:start}.card{min-width:0;border:1px solid #dce4ee;border-radius:6px;background:#fff;overflow:hidden}.card.list-card{max-height:calc(100vh - 76px);overflow:auto}.card.detail-card{position:sticky;top:64px;max-height:calc(100vh - 76px);overflow:auto;align-self:start}.head{display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:48px;padding:9px 12px;border-bottom:1px solid #e7edf4}.head h2{font-size:14px}.actions,.filter-actions{display:flex;align-items:center;gap:7px}.muted{color:#64748b;font-size:11px;line-height:1.5}
    button,input,select,textarea{font:inherit;color:#172033}button,a.button{display:inline-flex;align-items:center;justify-content:center;min-height:30px;padding:5px 9px;border:1px solid #cad6e6;border-radius:4px;background:#fff;cursor:pointer;text-decoration:none}button:hover,a.button:hover{border-color:#8ebcff}button:disabled{opacity:.45;cursor:not-allowed}.primary{background:#0b6ff6!important;color:#fff;border-color:#0b6ff6!important;font-weight:800}.secondary{color:#075ecf;border-color:#a9caff!important}.danger{color:#b42318;border-color:#efb4ae!important}label{display:grid;gap:4px;color:#475569;font-size:10px;font-weight:700}input,select,textarea{width:100%;min-height:32px;padding:5px 8px;border:1px solid #ced8e5;border-radius:4px;background:#fff}textarea{min-height:72px;resize:vertical}input:disabled,select:disabled,textarea:disabled{background:#f3f6fa;color:#64748b}
    .filters{display:grid;grid-template-columns:1fr 1fr;gap:8px;padding:10px 12px;border-bottom:1px solid #e7edf4}.wide{grid-column:1/-1}.family-table{width:100%;border-collapse:collapse;table-layout:fixed}.family-table th,.family-table td{padding:9px 8px;border-bottom:1px solid #edf1f6;text-align:left;font-size:11px;vertical-align:top}.family-table th{background:#f8faff;color:#64748b;font-size:10px}.family-table th:nth-child(2),.family-table td:nth-child(2){width:78px}.family-table th:last-child,.family-table td:last-child{width:54px}.family-table tbody tr{cursor:pointer}.family-table tbody tr:hover{background:#e7f0ff}.family-table tbody tr.selected{background:#d9e9ff;box-shadow:inset 3px 0 #0b6ff6}.family-name{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.capacity-list{display:block;margin-top:2px;color:#64748b;font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.review-flag{display:inline-block;margin-top:3px;padding:1px 4px;border-radius:3px;background:#fff1cc;color:#805b00;font-size:9px;font-weight:800}.status{display:inline-block;padding:2px 5px;border-radius:3px;background:#e7f7ed;color:#137333;font-size:10px;font-weight:800}.status.inactive{background:#eef1f5;color:#64748b}.empty{padding:28px 12px;text-align:center;color:#64748b}.pager{display:flex;align-items:center;justify-content:space-between;padding:9px 12px;border-top:1px solid #edf1f6}
    .tabs{display:flex;border-bottom:1px solid #dce4ee;padding:0 12px}.tab{border:0;border-bottom:2px solid transparent;border-radius:0;padding:10px 14px;color:#64748b}.tab.active{border-bottom-color:#0b6ff6;color:#075ecf;font-weight:800}.panel{padding:14px}.form-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.two{grid-column:span 2}.full{grid-column:1/-1}.section-title{grid-column:1/-1;margin-top:4px;padding-top:11px;border-top:1px solid #edf1f6;font-size:12px}.section-title:first-child{margin-top:0;padding-top:0;border:0}.check{display:flex;align-items:center;gap:7px;min-height:32px;color:#334155;font-size:11px}.check input{width:auto;min-height:auto}.detail-toolbar{display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:1px solid #e7edf4}.message{margin-right:auto;color:#64748b;font-size:11px}.message.error{color:#b42318}.form-actions{display:flex;align-items:end;justify-content:flex-end;gap:8px;margin-top:14px;padding-top:12px;border-top:1px solid #edf1f6}.reason{width:min(360px,48%)}
    .variant-create{display:grid;grid-template-columns:140px 120px minmax(140px,1fr) 150px auto;gap:8px;align-items:end;padding:11px 12px;border-bottom:1px solid #e7edf4;background:#f8fafc}.variants{width:100%;border-collapse:collapse;table-layout:fixed}.variants th,.variants td{padding:8px;border-bottom:1px solid #edf1f6;text-align:left;font-size:11px}.variants th{background:#f8faff;color:#64748b;font-size:10px}.variants th:first-child{width:130px}.variants th:nth-child(3){width:115px}.variants th:nth-child(4){width:74px}.variants th:last-child{width:72px}.variants td input,.variants td select{min-width:0}.variant-capacity{display:grid;grid-template-columns:1fr 75px;gap:5px}.code{font-family:"Roboto Mono",Consolas,monospace;color:#075ecf;font-size:10px;word-break:break-all}.locked{color:#9a6700;font-size:10px}.history{width:100%;border-collapse:collapse}.history th,.history td{padding:8px;border-bottom:1px solid #edf1f6;text-align:left;font-size:11px}.history th{background:#f8faff;color:#64748b;font-size:10px}.type-badge{font-size:10px;color:#526175}.new-variants{display:grid;gap:7px}.new-variant{display:grid;grid-template-columns:140px 120px minmax(140px,1fr) 150px auto;gap:8px;align-items:end;padding:9px;border:1px solid #e2e8f0;border-radius:5px}
    @media(max-width:1180px){.layout{grid-template-columns:1fr}.list-card{max-height:500px;overflow:auto}.detail-card{position:static;max-height:none}.variant-create,.new-variant{grid-template-columns:1fr 1fr 1fr auto}.variant-create label:nth-child(4),.new-variant label:nth-child(4){grid-column:1/3}}@media(max-width:720px){main{padding:8px}.filters,.form-grid{grid-template-columns:1fr}.wide,.two{grid-column:auto}.variant-create,.new-variant{grid-template-columns:1fr 1fr}.variant-create label:nth-child(3),.variant-create label:nth-child(4),.new-variant label:nth-child(3),.new-variant label:nth-child(4){grid-column:1/-1}.table-scroll{overflow:auto}.variants{min-width:760px}.reason{width:100%}.form-actions{flex-wrap:wrap;align-items:stretch}}
  </style>
</head>
<body>
  <header><h1>商品マスター</h1><div class="actions"><span class="muted">{{ $user->name }}</span><form method="post" action="{{ route('logout') }}">@csrf<button type="submit">ログアウト</button></form></div></header>
  <main><x-basic-master-tabs active="products" /><div class="layout">
    <section class="card list-card">
      <div class="head"><div><h2>商品群一覧</h2><p id="result-count" class="muted"></p></div>@if($canEdit)<button id="new-family" class="secondary" type="button">新規登録</button>@endif</div>
      <form id="filters" class="filters">
        <label class="wide">検索<input id="filter-q" placeholder="商品名・商品コード・Access旧コード"></label>
        <label>商品区分<select id="filter-type"><option value="">すべて</option><option value="sake">酒</option><option value="kasu">酒粕</option><option value="food">食品</option><option value="goods">グッズ・その他</option></select></label>
        <label>状態<select id="filter-active"><option value="active">有効</option><option value="inactive">休止</option><option value="all">すべて</option></select></label>
        <label class="wide">情報整備<select id="filter-missing"><option value="">指定なし</option><option value="any">必須情報に未設定あり</option><option value="capacity">容量未設定</option><option value="alcohol">アルコール分未設定</option><option value="tax">税区分未設定</option><option value="duplicate_capacity">同一容量が複数</option><option value="unpasteurized_review">名称に「生」あり・フラグ要確認</option></select></label>
        <div class="filter-actions wide"><button id="clear-filter" type="button">クリア</button><a id="export-csv" class="button" href="#">CSV抽出</a><button class="primary" type="submit">検索</button></div>
      </form>
      <table class="family-table"><thead><tr><th>商品群</th><th>区分</th><th>状態</th></tr></thead><tbody id="family-list"></tbody></table><div id="empty-list" class="empty" hidden>該当する商品群はありません。</div>
      <div class="pager"><button id="prev-page" type="button">前へ</button><span id="page-info" class="muted"></span><button id="next-page" type="button">次へ</button></div>
    </section>

    <section class="card detail-card">
      <div class="head"><div><h2 id="detail-title">商品群を選択</h2><p id="detail-subtitle" class="muted">一覧から選択してください。</p></div><button id="reload-family" type="button" disabled>再読込</button></div>
      <div class="detail-toolbar"><span id="detail-message" class="message"></span></div><div id="detail-empty" class="empty">商品群と容量・規格別商品を管理します。</div>
      <form id="family-form" hidden>@csrf
        <div class="tabs"><button class="tab active" data-tab="basic" type="button">基本情報</button><button class="tab" data-tab="variants" type="button">容量・規格</button><button class="tab" data-tab="history" type="button">変更履歴</button></div>
        <div class="panel" data-panel="basic"><div class="form-grid">
          <h3 class="section-title">商品群</h3><label class="two">商品群名<input id="name" maxlength="150" required placeholder="例：安芸虎 山田錦80％ 純米"></label><label class="two">フリガナ<input id="name-kana" maxlength="200"></label>
          <label>商品区分<select id="product-type"><option value="sake">酒</option><option value="kasu">酒粕</option><option value="food">食品</option><option value="goods">グッズ・その他</option></select></label><label>ブランド・銘柄<input id="brand-name" maxlength="120"></label><label>カテゴリ<input id="category-name" maxlength="120"></label><label>消費税区分<select id="tax-category">@foreach($taxCategories as $item)<option value="{{ $item->id }}">{{ $item->name }}</option>@endforeach</select></label>
          <div id="sake-fields" class="form-grid full" style="display:grid">
            <h3 class="section-title">酒類情報</h3><label>アルコール分（%）<input id="alcohol" type="number" min="0" max="100" step="0.01"></label><label>酒税区分コード<input id="liquor-tax-code" maxlength="80" placeholder="例：sake"></label><label>酒類名<input id="liquor-type-name" maxlength="120" placeholder="例：清酒"></label><label>精米歩合（%）<input id="polishing" type="number" min="0" max="100" step="0.01"></label><label class="two">原材料<textarea id="ingredients" maxlength="2000"></textarea></label><label class="two">製造方法<input id="production-method" maxlength="120"></label><label class="check full"><input id="unpasteurized" type="checkbox">生酒（無印は火入として保存）</label>
          </div>
          <h3 class="section-title">運用</h3><label class="check"><input id="sales-available" type="checkbox">販売対象</label><label class="check"><input id="inventory-managed" type="checkbox">在庫管理対象</label><label class="check"><input id="family-active" type="checkbox">有効</label><label class="full">メモ<textarea id="note" maxlength="5000"></textarea></label>
          <div id="new-variants-section" class="full" hidden><h3 class="section-title">初期容量・規格</h3><div id="new-variants" class="new-variants"></div><button id="add-new-variant" type="button">行を追加</button></div>
        </div></div>
        <div data-panel="variants" hidden>
          @if($canEdit)<div class="variant-create"><label>容量<input id="add-capacity" type="number" min="0" step="0.0001"></label><label>単位<select id="add-capacity-unit">@foreach($units as $unit)<option value="{{ $unit->id }}" data-code="{{ $unit->code }}">{{ $unit->symbol ?: $unit->name }}</option>@endforeach</select></label><label>規格表示<input id="add-variant-label" maxlength="120" placeholder="容量から自動作成"></label><label>商品コード<input id="add-product-code" maxlength="80" placeholder="空欄で自動採番"></label><button id="add-variant" class="secondary" type="button">追加</button></div>@endif
          <div class="table-scroll"><table class="variants"><thead><tr><th>商品コード</th><th>商品表示名・規格</th><th>容量</th><th>状態</th><th></th></tr></thead><tbody id="variant-list"></tbody></table></div><div id="variant-empty" class="empty" hidden>容量・規格別商品はありません。</div>
        </div>
        <div class="panel" data-panel="history" hidden><table class="history"><thead><tr><th>日時</th><th>担当者</th><th>内容</th><th>理由</th></tr></thead><tbody id="history-list"></tbody></table><div id="history-empty" class="empty">変更履歴はまだありません。</div></div>
        <div class="form-actions"><span id="form-message" class="message"></span><label id="reason-label" class="reason">変更理由<input id="change-reason" maxlength="1000" placeholder="例：商品情報の更新"></label>@if($canEdit)<button class="primary" type="submit">商品群を保存</button>@endif</div>
      </form>
    </section>
  </div></main>
  <script>
    const canEdit=@json($canEdit),units=@json($units),taxCategories=@json($taxCategories),state={page:1,lastPage:1,selectedId:null,selected:null,isNew:false,dirty:false};
    const el=id=>document.getElementById(id),typeLabels={sake:'酒',kasu:'酒粕',food:'食品',goods:'グッズ・その他'},labels={name:'商品群名',product_type:'商品区分',consumption_tax_category_id:'消費税区分',alcohol_percentage:'アルコール分',liquor_tax_category_code:'酒税区分',change_reason:'変更理由'};
    const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('input[name="_token"]')?.value||''},...options});const data=await response.json().catch(()=>({}));if(!response.ok){const errors=data.errors?Object.entries(data.errors).map(([key,value])=>`${labels[key]||key}: ${value[0]}`).join(' / '):null;throw new Error(errors||data.message||'処理に失敗しました。')}return data.data};
    const query=(includePage=true)=>{const p=new URLSearchParams();const values={q:el('filter-q').value.trim(),product_type:el('filter-type').value,active:el('filter-active').value,missing:el('filter-missing').value};Object.entries(values).forEach(([k,v])=>v&&p.set(k,v));if(includePage){p.set('page',state.page);p.set('per_page','30')}return p};
    const msg=(node,text,error=false)=>{node.textContent=text;node.classList.toggle('error',error)};const confirmDiscard=()=>!state.dirty||confirm('保存していない変更があります。破棄しますか？');
    async function loadList(){try{const data=await api(`/api/v1/masters/product-families?${query()}`);state.lastPage=data.pagination.last_page;renderList(data.product_families,data.pagination);el('export-csv').href=`/api/v1/masters/product-families/export?${query(false)}`;}catch(error){msg(el('detail-message'),error.message,true)}}
    function renderList(items,p){const body=el('family-list');body.innerHTML='';items.forEach(item=>{const row=document.createElement('tr');row.classList.toggle('selected',String(item.id)===String(state.selectedId));const name=document.createElement('td');name.innerHTML='<strong class="family-name"></strong><span class="capacity-list"></span>';name.querySelector('strong').textContent=item.name;name.querySelector('span').textContent=item.capacity_labels.join(' / ')||'規格未設定';if(item.needs_unpasteurized_review){const flag=document.createElement('span');flag.className='review-flag';flag.textContent='生酒フラグ要確認';name.appendChild(flag)}const type=document.createElement('td');type.innerHTML=`<span class="type-badge">${typeLabels[item.product_type]||item.product_type}</span>`;const status=document.createElement('td');status.innerHTML=`<span class="status${item.is_active?'':' inactive'}">${item.is_active?'有効':'休止'}</span>`;row.append(name,type,status);row.onclick=()=>selectFamily(item.id);body.appendChild(row)});el('empty-list').hidden=items.length>0;el('result-count').textContent=`${p.total.toLocaleString()}件`;el('page-info').textContent=`${p.current_page} / ${Math.max(1,p.last_page)}ページ`;el('prev-page').disabled=p.current_page<=1;el('next-page').disabled=p.current_page>=p.last_page}
    async function selectFamily(id){if(String(id)===String(state.selectedId)&&!state.isNew)return;if(!confirmDiscard())return;state.selectedId=id;state.isNew=false;await loadFamily(id);await loadList()}
    async function loadFamily(id){msg(el('detail-message'),'読み込み中です。');try{const data=await api(`/api/v1/masters/product-families/${id}`);state.selected=data.product_family;fillFamily(data.product_family);showForm();msg(el('detail-message'),'')}catch(error){msg(el('detail-message'),error.message,true)}}
    function fillFamily(f){el('name').value=f.name;el('name-kana').value=f.name_kana||'';el('product-type').value=f.product_type;el('product-type').disabled=true;el('brand-name').value=f.brand_name||'';el('category-name').value=f.category_name||'';el('tax-category').value=f.consumption_tax_category_id||'';el('alcohol').value=f.alcohol_percentage??'';el('liquor-tax-code').value=f.liquor_tax_category_code||'';el('liquor-type-name').value=f.liquor_type_name||'';el('ingredients').value=f.ingredients||'';el('polishing').value=f.rice_polishing_ratio??'';el('production-method').value=f.production_method||'';el('unpasteurized').checked=!!f.is_unpasteurized;el('sales-available').checked=!!f.is_sales_available;el('inventory-managed').checked=!!f.is_inventory_managed;el('family-active').checked=!!f.is_active;el('note').value=f.note||'';el('change-reason').value='';el('detail-title').textContent=f.name;el('detail-subtitle').textContent=`${typeLabels[f.product_type]} / ${f.products.length}規格${f.is_unpasteurized?' / 生酒':' / 火入'}`;el('new-variants-section').hidden=true;el('reason-label').hidden=!canEdit;toggleSake();renderVariants(f.products);renderHistory(f.history||[]);setDisabled(!canEdit);state.dirty=false}
    function showForm(){el('detail-empty').hidden=true;el('family-form').hidden=false;el('reload-family').disabled=false}
    function newFamily(){if(!confirmDiscard())return;state.selectedId=null;state.selected=null;state.isNew=true;el('family-form').reset();el('product-type').disabled=false;el('sales-available').checked=true;el('inventory-managed').checked=true;el('family-active').checked=true;el('unpasteurized').checked=false;const reduced=taxCategories.find(x=>x.is_reduced_rate),standard=taxCategories.find(x=>!x.is_reduced_rate);el('tax-category').value=String(standard?.id||taxCategories[0]?.id||'');el('detail-title').textContent='新しい商品群';el('detail-subtitle').textContent='商品名を1度入力し、容量・規格を追加します。';el('new-variants-section').hidden=false;el('reason-label').hidden=true;el('new-variants').innerHTML='';addNewVariant();renderVariants([]);renderHistory([]);showForm();toggleSake();activateTab('basic');setDisabled(!canEdit);state.dirty=false;el('name').focus()}
    function setDisabled(disabled){el('family-form').querySelectorAll('input,select,textarea').forEach(input=>{if(input.id==='product-type'&&!state.isNew){input.disabled=true;return}input.disabled=disabled});document.querySelectorAll('#variant-list button,#add-variant').forEach(button=>button.disabled=disabled)}
    function toggleSake(){const sake=el('product-type').value==='sake';el('sake-fields').hidden=!sake;if(state.isNew){const wanted=sake?'milliliter':el('product-type').value==='kasu'?'gram':'piece';document.querySelectorAll('.new-capacity-unit').forEach(select=>select.value=String(units.find(x=>x.code===wanted)?.id||units[0]?.id||''));el('add-capacity-unit').value=String(units.find(x=>x.code===wanted)?.id||units[0]?.id||'')}}
    function familyPayload(){const sake=el('product-type').value==='sake';return{name:el('name').value.trim(),name_kana:el('name-kana').value.trim()||null,product_type:el('product-type').value,brand_name:el('brand-name').value.trim()||null,category_name:el('category-name').value.trim()||null,consumption_tax_category_id:Number(el('tax-category').value),alcohol_percentage:sake&&el('alcohol').value?Number(el('alcohol').value):null,liquor_tax_category_code:sake?el('liquor-tax-code').value.trim()||null:null,liquor_type_name:sake?el('liquor-type-name').value.trim()||null:null,ingredients:sake?el('ingredients').value.trim()||null:null,rice_polishing_ratio:sake&&el('polishing').value?Number(el('polishing').value):null,production_method:sake?el('production-method').value.trim()||null:null,is_unpasteurized:sake&&el('unpasteurized').checked,is_sales_available:el('sales-available').checked,is_inventory_managed:el('inventory-managed').checked,is_active:el('family-active').checked,note:el('note').value.trim()||null,change_reason:el('change-reason').value.trim()||null}}
    function addNewVariant(){const row=document.createElement('div');row.className='new-variant';row.innerHTML=`<label>容量<input class="new-capacity" type="number" min="0" step="0.0001"></label><label>単位<select class="new-capacity-unit">${units.map(x=>`<option value="${x.id}">${x.symbol||x.name}</option>`).join('')}</select></label><label>規格表示<input class="new-label" maxlength="120" placeholder="容量から自動作成"></label><label>商品コード<input class="new-code" maxlength="80" placeholder="空欄で自動採番"></label><button class="danger remove-new" type="button">削除</button>`;row.querySelector('.remove-new').onclick=()=>{if(el('new-variants').children.length>1)row.remove()};el('new-variants').appendChild(row);toggleSake()}
    function newVariantsPayload(){return [...el('new-variants').children].map(row=>({product_code:row.querySelector('.new-code').value.trim()||null,capacity_value:row.querySelector('.new-capacity').value?Number(row.querySelector('.new-capacity').value):null,capacity_unit_id:row.querySelector('.new-capacity-unit').value?Number(row.querySelector('.new-capacity-unit').value):null,variant_label:row.querySelector('.new-label').value.trim()||null,is_active:true}))}
    async function saveFamily(event){event.preventDefault();if(!canEdit)return;const body=familyPayload();if(state.isNew)body.variants=newVariantsPayload();if(!state.isNew&&!body.change_reason){msg(el('form-message'),'変更理由を入力してください。',true);return}msg(el('form-message'),'保存中です。');try{const data=await api(state.isNew?'/api/v1/masters/product-families':`/api/v1/masters/product-families/${state.selectedId}`,{method:state.isNew?'POST':'PUT',body:JSON.stringify(body)});state.selectedId=data.product_family.id;state.isNew=false;state.dirty=false;await loadFamily(state.selectedId);await loadList();msg(el('form-message'),'保存しました。')}catch(error){msg(el('form-message'),error.message,true)}}
    function renderVariants(items){const body=el('variant-list');body.innerHTML='';items.forEach(item=>{const row=document.createElement('tr');row.dataset.id=item.id;const code=document.createElement('td');code.innerHTML=`<span class="code"></span><div class="muted"></div>`;code.querySelector('.code').textContent=item.product_code;code.querySelector('.muted').textContent=item.legacy_code?`Access: ${item.legacy_code}`:'';const display=document.createElement('td');display.innerHTML=`<strong></strong><input class="variant-label" maxlength="120">${item.is_package_locked?'<div class="locked">容量は履歴ありのため固定</div>':''}`;display.querySelector('strong').textContent=item.display_name;display.querySelector('input').value=item.variant_label||'';const capacity=document.createElement('td');capacity.innerHTML=`<div class="variant-capacity"><input class="capacity" type="number" min="0" step="0.0001"><select class="capacity-unit">${units.map(x=>`<option value="${x.id}">${x.symbol||x.name}</option>`).join('')}</select></div>`;capacity.querySelector('input').value=item.capacity_value??'';capacity.querySelector('select').value=item.capacity_unit_id??'';capacity.querySelectorAll('input,select').forEach(input=>input.disabled=item.is_package_locked||!canEdit);const active=document.createElement('td');active.innerHTML='<label class="check"><input class="variant-active" type="checkbox">有効</label>';active.querySelector('input').checked=!!item.is_active;active.querySelector('input').disabled=!canEdit;const action=document.createElement('td');const save=document.createElement('button');save.type='button';save.textContent='保存';save.disabled=!canEdit;save.onclick=()=>saveVariant(row,item);action.appendChild(save);row.append(code,display,capacity,active,action);body.appendChild(row)});el('variant-empty').hidden=items.length>0}
    async function saveVariant(row,item){const reason=el('change-reason').value.trim();if(!reason){msg(el('form-message'),'容量・規格の変更にも変更理由が必要です。',true);return}const body={capacity_value:row.querySelector('.capacity').value?Number(row.querySelector('.capacity').value):null,capacity_unit_id:row.querySelector('.capacity-unit').value?Number(row.querySelector('.capacity-unit').value):null,variant_label:row.querySelector('.variant-label').value.trim()||null,is_active:row.querySelector('.variant-active').checked,change_reason:reason};try{await api(`/api/v1/masters/product-families/${state.selectedId}/products/${item.id}`,{method:'PUT',body:JSON.stringify(body)});await loadFamily(state.selectedId);msg(el('form-message'),'容量・規格を保存しました。')}catch(error){msg(el('form-message'),error.message,true)}}
    async function addVariant(){const body={product_code:el('add-product-code').value.trim()||null,capacity_value:el('add-capacity').value?Number(el('add-capacity').value):null,capacity_unit_id:el('add-capacity-unit').value?Number(el('add-capacity-unit').value):null,variant_label:el('add-variant-label').value.trim()||null,is_active:true,change_reason:el('change-reason').value.trim()||null};try{await api(`/api/v1/masters/product-families/${state.selectedId}/products`,{method:'POST',body:JSON.stringify(body)});['add-product-code','add-capacity','add-variant-label'].forEach(id=>el(id).value='');await loadFamily(state.selectedId);await loadList();msg(el('form-message'),'容量・規格を追加しました。')}catch(error){msg(el('form-message'),error.message,true)}}
    function renderHistory(items){const body=el('history-list');body.innerHTML='';items.forEach(item=>{const row=document.createElement('tr');[item.occurred_at?new Date(item.occurred_at).toLocaleString('ja-JP'):'-',item.user_name||'-',item.event||'-',item.reason||'-'].forEach(text=>{const cell=document.createElement('td');cell.textContent=text;row.appendChild(cell)});body.appendChild(row)});el('history-empty').hidden=items.length>0}
    function activateTab(name){document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.tab===name));document.querySelectorAll('[data-panel]').forEach(panel=>panel.hidden=panel.dataset.panel!==name)}
    el('filters').onsubmit=e=>{e.preventDefault();state.page=1;loadList()};el('clear-filter').onclick=()=>{el('filters').reset();state.page=1;loadList()};el('prev-page').onclick=()=>{if(state.page>1){state.page--;loadList()}};el('next-page').onclick=()=>{if(state.page<state.lastPage){state.page++;loadList()}};el('new-family')?.addEventListener('click',newFamily);el('reload-family').onclick=()=>state.selectedId&&loadFamily(state.selectedId);el('family-form').onsubmit=saveFamily;el('product-type').onchange=toggleSake;el('add-new-variant').onclick=addNewVariant;el('add-variant')?.addEventListener('click',addVariant);document.querySelectorAll('.tab').forEach(tab=>tab.onclick=()=>activateTab(tab.dataset.tab));el('family-form').addEventListener('input',()=>state.dirty=true);el('family-form').addEventListener('change',()=>state.dirty=true);window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue=''}});loadList();
  </script>
</body>
</html>
