<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * @var array<string, array<string, string>>
     */
    private array $columnComments = [
        'migrations' => [
            'id' => 'このマイグレーション履歴を一意に識別するID',
            'migration' => '実行済みマイグレーションのクラス名またはファイル名',
            'batch' => '同じタイミングで実行されたマイグレーションのバッチ番号',
        ],
        'employees' => [
            'id' => '従業員レコードを一意に識別するID',
            'employee_code' => '社内で従業員を識別するコード',
            'name' => '従業員の氏名',
            'name_kana' => '従業員名のカナ表記',
            'email' => '従業員の連絡先メールアドレス',
            'phone' => '従業員の電話番号',
            'department' => '所属部署名',
            'position' => '役職名',
            'is_active' => '現在この従業員を有効として扱うかどうか',
            'disabled_at' => '従業員を無効化した日時',
            'created_at' => 'この従業員レコードを作成した日時',
            'updated_at' => 'この従業員レコードを最後に更新した日時',
        ],
        'users' => [
            'id' => 'ユーザーレコードを一意に識別するID',
            'employee_id' => '紐づく従業員マスタのID',
            'name' => 'ログインユーザーの表示名',
            'email' => 'ログインに使用するメールアドレス',
            'email_verified_at' => 'メールアドレス確認が完了した日時',
            'password' => 'ログイン認証用のパスワードハッシュ',
            'remember_token' => 'ログイン維持機能で使用するトークン',
            'is_active' => '現在このユーザーを有効として扱うかどうか',
            'disabled_at' => 'ユーザーを無効化した日時',
            'last_login_at' => '最後にログインした日時',
            'created_at' => 'このユーザーレコードを作成した日時',
            'updated_at' => 'このユーザーレコードを最後に更新した日時',
        ],
        'roles' => [
            'id' => 'ロールレコードを一意に識別するID',
            'code' => 'ロールを識別するコード',
            'name' => 'ロール名',
            'description' => 'ロールの用途や権限範囲の説明',
            'is_system' => 'システム標準ロールであることを示すフラグ',
            'is_active' => '現在このロールを有効として扱うかどうか',
            'created_at' => 'このロールを作成した日時',
            'updated_at' => 'このロールを最後に更新した日時',
        ],
        'permissions' => [
            'id' => '権限レコードを一意に識別するID',
            'code' => '権限を識別するコード',
            'name' => '権限名',
            'description' => '権限の内容や用途の説明',
            'is_system' => 'システム標準権限であることを示すフラグ',
            'is_active' => '現在この権限を有効として扱うかどうか',
            'created_at' => 'この権限を作成した日時',
            'updated_at' => 'この権限を最後に更新した日時',
        ],
        'role_user' => [
            'id' => 'ユーザーロール紐付レコードを一意に識別するID',
            'role_id' => '付与するロールのID',
            'user_id' => 'ロールを付与するユーザーのID',
            'created_at' => 'ロールをユーザーに付与した日時',
            'updated_at' => 'この紐付レコードを最後に更新した日時',
        ],
        'permission_role' => [
            'id' => 'ロール権限紐付レコードを一意に識別するID',
            'permission_id' => 'ロールに含める権限のID',
            'role_id' => '権限を付与するロールのID',
            'created_at' => '権限をロールに紐付けた日時',
            'updated_at' => 'この紐付レコードを最後に更新した日時',
        ],
        'audit_logs' => [
            'id' => '監査ログレコードを一意に識別するID',
            'occurred_at' => '監査対象の操作が実際に発生した日時',
            'user_id' => '操作を実行したユーザーのID',
            'approved_by_user_id' => '承認付き操作の場合の承認ユーザーID',
            'event' => '記録対象となった操作やイベントの名称',
            'auditable_type' => '監査対象モデルの型名',
            'auditable_id' => '監査対象モデルの識別子',
            'target_table' => '変更対象となったテーブル名',
            'target_id' => '変更対象レコードの識別子',
            'before_values' => '変更前の値を保持するJSON',
            'after_values' => '変更後の値を保持するJSON',
            'reason' => '操作理由や補足説明',
            'ip_address' => '操作元クライアントのIPアドレス',
            'user_agent' => '操作元クライアントのユーザーエージェント',
            'request_id' => '同一リクエストを追跡するためのID',
            'created_at' => 'この監査ログレコードを保存した日時',
        ],
        'number_sequences' => [
            'id' => '採番設定レコードを一意に識別するID',
            'code' => '採番設定を識別するコード',
            'name' => '採番設定の名称',
            'prefix' => '採番値の前に付ける接頭辞',
            'suffix' => '採番値の後に付ける接尾辞',
            'current_number' => '現在までに採番された最新番号',
            'padding_length' => '番号部分をゼロ埋めする桁数',
            'reset_type' => '番号をリセットする周期種別',
            'last_reset_on' => '最後に番号をリセットした日付',
            'description' => '採番ルールの補足説明',
            'is_active' => '現在この採番設定を有効として扱うかどうか',
            'created_at' => 'この採番設定を作成した日時',
            'updated_at' => 'この採番設定を最後に更新した日時',
        ],
        'transaction_categories' => [
            'id' => '取引区分レコードを一意に識別するID',
            'code' => '取引区分を識別するコード',
            'name' => '取引区分名',
            'description' => '取引区分の意味や用途の説明',
            'sort_order' => '画面や帳票での表示順',
            'is_active' => '現在この取引区分を有効として扱うかどうか',
            'created_at' => 'この取引区分を作成した日時',
            'updated_at' => 'この取引区分を最後に更新した日時',
        ],
        'settlement_receivable_categories' => [
            'id' => '売掛・精算区分レコードを一意に識別するID',
            'code' => '売掛・精算区分を識別するコード',
            'name' => '売掛・精算区分名',
            'receivable_method' => '売掛金の扱い方を表す方式',
            'export_type' => '出荷や輸出区分としての扱い',
            'liquor_tax_type' => '酒税上の扱い区分',
            'consumption_tax_type' => '消費税上の扱い区分',
            'accounting_code' => '会計連携時に使用する科目コード',
            'sub_accounting_code' => '会計連携時に使用する補助科目コード',
            'department_code' => '会計連携時に使用する部門コード',
            'invoice_required' => 'この区分で請求書発行が必要かどうか',
            'reduces_stock' => '出荷時に在庫を減算する対象かどうか',
            'description' => '区分の補足説明',
            'is_active' => '現在この区分を有効として扱うかどうか',
            'created_at' => 'この区分を作成した日時',
            'updated_at' => 'この区分を最後に更新した日時',
        ],
        'billing_cycles' => [
            'id' => '請求サイクルレコードを一意に識別するID',
            'code' => '請求サイクルを識別するコード',
            'name' => '請求サイクル名',
            'closing_day' => '請求締め日に使う日付',
            'payment_month_offset' => '締月から何か月後に入金予定とするか',
            'payment_day' => '入金予定日として使う日付',
            'billing_method' => '請求の作り方を表す方式',
            'description' => '請求サイクルの補足説明',
            'is_active' => '現在この請求サイクルを有効として扱うかどうか',
            'created_at' => 'この請求サイクルを作成した日時',
            'updated_at' => 'この請求サイクルを最後に更新した日時',
        ],
        'customers' => [
            'id' => '取引先レコードを一意に識別するID',
            'customer_code' => '取引先を識別するコード',
            'name' => '正式な取引先名',
            'name_kana' => '取引先名のカナ表記',
            'short_name' => '略称や短縮表示名',
            'billing_name' => '請求書に表示する請求先名',
            'postal_code' => '取引先住所の郵便番号',
            'address1' => '住所の1行目',
            'address2' => '住所の2行目',
            'phone' => '代表電話番号',
            'fax' => 'FAX番号',
            'email' => '主連絡先メールアドレス',
            'contact_name' => '主担当者名',
            'transaction_category_id' => 'この取引先に適用する取引区分のID',
            'settlement_receivable_category_id' => 'この取引先に適用する売掛・精算区分のID',
            'billing_cycle_id' => 'この取引先に適用する請求サイクルのID',
            'tax_rounding_method' => '消費税計算時の端数処理方法',
            'tax_calculation_unit' => '消費税を明細単位か伝票単位かで計算する設定',
            'amount_rounding_method' => '金額計算時の端数処理方法',
            'invoice_required' => 'この取引先に請求書発行が必要かどうか',
            'search_key' => '検索しやすくするための補助キー',
            'legacy_code' => '旧システムで使っていた取引先コード',
            'legacy_name' => '旧システムで使っていた取引先名',
            'note' => '取引先に関する備考',
            'is_active' => '現在この取引先を有効として扱うかどうか',
            'disabled_at' => '取引先を無効化した日時',
            'created_at' => 'この取引先レコードを作成した日時',
            'updated_at' => 'この取引先レコードを最後に更新した日時',
        ],
        'units' => [
            'id' => '単位レコードを一意に識別するID',
            'code' => '単位を識別するコード',
            'name' => '単位名',
            'symbol' => '画面や帳票に表示する単位記号',
            'unit_type' => '数量・容量などの単位種別',
            'decimal_scale' => 'この単位で通常扱う小数桁数',
            'description' => '単位の補足説明',
            'is_active' => '現在この単位を有効として扱うかどうか',
            'created_at' => 'この単位を作成した日時',
            'updated_at' => 'この単位を最後に更新した日時',
        ],
        'products' => [
            'id' => '商品レコードを一意に識別するID',
            'product_code' => '商品を識別するコード',
            'product_type' => '清酒・食品などの商品種別',
            'name' => '正式な商品名',
            'name_kana' => '商品名のカナ表記',
            'display_name' => '画面や帳票に表示する商品名',
            'brand_name' => 'ブランド名',
            'series_name' => 'シリーズ名',
            'category_name' => '分類用カテゴリ名',
            'consumption_tax_category_id' => 'この商品に標準適用する消費税区分のID',
            'base_unit_id' => '商品管理の基準となる単位ID',
            'sales_unit_id' => '販売時の標準単位ID',
            'inventory_unit_id' => '在庫管理時の標準単位ID',
            'capacity_value' => '内容量や容量の数値',
            'capacity_unit_id' => '内容量や容量に対応する単位ID',
            'alcohol_percentage' => 'アルコール度数',
            'is_alcohol' => '酒税対象となる酒類商品かどうか',
            'is_sales_available' => '販売対象として扱うかどうか',
            'is_inventory_managed' => '在庫管理対象として扱うかどうか',
            'search_key' => '検索しやすくするための補助キー',
            'legacy_code' => '旧システムで使っていた商品コード',
            'legacy_name' => '旧システムで使っていた商品名',
            'note' => '商品に関する備考',
            'is_active' => '現在この商品を有効として扱うかどうか',
            'disabled_at' => '商品を無効化した日時',
            'created_at' => 'この商品レコードを作成した日時',
            'updated_at' => 'この商品レコードを最後に更新した日時',
        ],
        'sake_product_details' => [
            'id' => '清酒商品詳細レコードを一意に識別するID',
            'product_id' => '対象となる商品のID',
            'liquor_tax_category_code' => '清酒商品の酒税区分コード',
            'liquor_type_name' => '酒類種別の表示名',
            'ingredients' => '原材料表示',
            'rice_polishing_ratio' => '精米歩合',
            'production_method' => '製法や造りの種別',
            'is_unpasteurized' => '生酒かどうかを示すフラグ',
            'created_at' => 'この詳細レコードを作成した日時',
            'updated_at' => 'この詳細レコードを最後に更新した日時',
        ],
        'kasu_product_details' => [
            'id' => '酒粕商品詳細レコードを一意に識別するID',
            'product_id' => '対象となる商品のID',
            'kasu_type' => '酒粕の種別',
            'storage_method' => '推奨保管方法',
            'created_at' => 'この詳細レコードを作成した日時',
            'updated_at' => 'この詳細レコードを最後に更新した日時',
        ],
        'food_product_details' => [
            'id' => '食品商品詳細レコードを一意に識別するID',
            'product_id' => '対象となる商品のID',
            'food_category' => '食品カテゴリ',
            'allergen_note' => 'アレルゲンに関する注記',
            'storage_method' => '推奨保管方法',
            'shelf_life_days' => '想定賞味期限日数',
            'created_at' => 'この詳細レコードを作成した日時',
            'updated_at' => 'この詳細レコードを最後に更新した日時',
        ],
        'goods_product_details' => [
            'id' => '物品商品詳細レコードを一意に識別するID',
            'product_id' => '対象となる商品のID',
            'goods_category' => '物品カテゴリ',
            'material' => '主な材質',
            'size_description' => 'サイズや寸法の説明',
            'created_at' => 'この詳細レコードを作成した日時',
            'updated_at' => 'この詳細レコードを最後に更新した日時',
        ],
        'unit_conversions' => [
            'id' => '単位換算レコードを一意に識別するID',
            'product_id' => '特定商品専用換算の場合の対象商品ID',
            'from_unit_id' => '換算元となる単位のID',
            'to_unit_id' => '換算先となる単位のID',
            'factor' => '換算に使用する倍率',
            'rounding_method' => '換算後の端数処理方法',
            'is_active' => '現在この換算ルールを有効として扱うかどうか',
            'created_at' => 'この換算ルールを作成した日時',
            'updated_at' => 'この換算ルールを最後に更新した日時',
        ],
        'price_lists' => [
            'id' => '価格表レコードを一意に識別するID',
            'code' => '価格表を識別するコード',
            'name' => '価格表名',
            'price_type' => '標準価格などの価格種別',
            'description' => '価格表の用途や補足説明',
            'is_active' => '現在この価格表を有効として扱うかどうか',
            'created_at' => 'この価格表を作成した日時',
            'updated_at' => 'この価格表を最後に更新した日時',
        ],
        'price_rules' => [
            'id' => '価格ルールレコードを一意に識別するID',
            'price_list_id' => '属する価格表のID',
            'product_id' => '価格を適用する商品のID',
            'customer_id' => '特定取引先向け価格の場合の取引先ID',
            'transaction_category_id' => '特定取引区分向け価格の場合の取引区分ID',
            'unit_id' => 'この価格が適用される単位のID',
            'unit_price' => '適用する単価',
            'currency' => '単価の通貨コード',
            'priority' => '複数候補がある場合の優先順位',
            'effective_from' => 'この価格ルールの適用開始日',
            'effective_to' => 'この価格ルールの適用終了日',
            'rounding_method' => '価格計算時の端数処理方法',
            'reason' => 'この価格を設定した理由',
            'is_active' => '現在この価格ルールを有効として扱うかどうか',
            'created_at' => 'この価格ルールを作成した日時',
            'updated_at' => 'この価格ルールを最後に更新した日時',
        ],
        'consumption_tax_categories' => [
            'id' => '消費税区分レコードを一意に識別するID',
            'code' => '消費税区分を識別するコード',
            'name' => '消費税区分名',
            'taxability' => '課税・非課税などの課税区分',
            'requires_tax_rate' => '税率マスタ参照が必要な区分かどうか',
            'is_reduced_rate' => '軽減税率対象区分かどうか',
            'is_export_exempt' => '輸出免税扱いかどうか',
            'is_invoice_display_target' => '請求書に税区分表示する対象かどうか',
            'sort_order' => '画面や帳票での表示順',
            'description' => '区分の補足説明',
            'is_active' => '現在この消費税区分を有効として扱うかどうか',
            'created_at' => 'この消費税区分を作成した日時',
            'updated_at' => 'この消費税区分を最後に更新した日時',
        ],
        'consumption_tax_rates' => [
            'id' => '消費税率レコードを一意に識別するID',
            'consumption_tax_category_id' => '属する消費税区分のID',
            'name' => '税率の名称',
            'rate' => '適用する消費税率',
            'effective_from' => 'この税率の適用開始日',
            'effective_to' => 'この税率の適用終了日',
            'description' => '税率の補足説明',
            'is_active' => '現在この税率を有効として扱うかどうか',
            'created_at' => 'この税率を作成した日時',
            'updated_at' => 'この税率を最後に更新した日時',
        ],
        'liquor_tax_categories' => [
            'id' => '酒税区分レコードを一意に識別するID',
            'code' => '酒税区分を識別するコード',
            'name' => '酒税区分名',
            'taxability' => '課税・免税などの酒税区分',
            'aggregate0' => '酒税集計で使う第1分類',
            'aggregate1' => '酒税集計で使う第2分類',
            'aggregate2' => '酒税集計で使う第3分類',
            'aggregate3' => '酒税集計で使う第4分類',
            'print_order' => '帳票出力時の表示順',
            'reduction_rate' => '標準の軽減率',
            'description' => '区分の補足説明',
            'is_active' => '現在この酒税区分を有効として扱うかどうか',
            'created_at' => 'この酒税区分を作成した日時',
            'updated_at' => 'この酒税区分を最後に更新した日時',
        ],
        'liquor_tax_rules' => [
            'id' => '酒税ルールレコードを一意に識別するID',
            'liquor_tax_category_id' => '適用先となる酒税区分のID',
            'code' => '酒税ルールを識別するコード',
            'name' => '酒税ルール名',
            'calculation_method' => '酒税の計算方法',
            'tax_per_kl' => '1キロリットル当たりの酒税額',
            'alcohol_percentage_min' => '適用対象となる最低アルコール度数',
            'alcohol_percentage_max' => '適用対象となる最高アルコール度数',
            'base_alcohol_percentage' => '計算基準となるアルコール度数',
            'additional_tax_per_kl_per_percent' => '度数超過分の加算酒税額',
            'reduction_rate' => 'このルールに適用する軽減率',
            'special_provision_code' => '特例や法令区分を表すコード',
            'effective_from' => 'この酒税ルールの適用開始日',
            'effective_to' => 'この酒税ルールの適用終了日',
            'description' => '酒税ルールの補足説明',
            'is_active' => '現在この酒税ルールを有効として扱うかどうか',
            'created_at' => 'この酒税ルールを作成した日時',
            'updated_at' => 'この酒税ルールを最後に更新した日時',
        ],
        'sales_orders' => [
            'id' => '受注ヘッダを一意に識別するID',
            'order_number' => '受注を一意に識別する受注番号',
            'status' => '受注の現在の進行状態',
            'customer_id' => '受注先となる取引先のID',
            'transaction_category_id' => '受注に適用する取引区分のID',
            'settlement_receivable_category_id' => '受注に適用する売掛・精算区分のID',
            'billing_cycle_id' => '受注に適用する請求サイクルのID',
            'order_date' => '受注を受け付けた日付',
            'requested_shipment_date' => '取引先から希望された出荷日',
            'requested_delivery_date' => '取引先から希望された納品日',
            'billing_target_date' => '請求対象として扱う基準日',
            'customer_order_number' => '取引先側の注文番号',
            'source_type' => '受注の起票元種別',
            'source_reference' => '起票元を参照するための文字列',
            'cancelled_reason' => '受注を取り消した理由',
            'cancelled_at' => '受注を取り消した日時',
            'note' => '受注に関する備考',
            'created_at' => 'この受注を作成した日時',
            'updated_at' => 'この受注を最後に更新した日時',
        ],
        'sales_order_lines' => [
            'id' => '受注明細を一意に識別するID',
            'sales_order_id' => '属する受注ヘッダのID',
            'line_no' => '受注明細の行番号',
            'product_id' => '受注した商品のID',
            'quantity' => '受注した数量',
            'unit_id' => '受注数量の単位ID',
            'remaining_quantity' => 'まだ出荷指示等に回っていない残数量',
            'note' => '受注明細に関する備考',
            'created_at' => 'この受注明細を作成した日時',
            'updated_at' => 'この受注明細を最後に更新した日時',
        ],
        'shipment_instructions' => [
            'id' => '出荷指示ヘッダを一意に識別するID',
            'instruction_number' => '出荷指示を一意に識別する番号',
            'status' => '出荷指示の現在の進行状態',
            'customer_id' => '出荷先となる取引先のID',
            'instruction_date' => '出荷指示を作成した日付',
            'scheduled_shipment_date' => '予定している出荷日',
            'stock_location_id' => '主に出荷に使う在庫場所のID',
            'cancelled_reason' => '出荷指示を取り消した理由',
            'cancelled_at' => '出荷指示を取り消した日時',
            'note' => '出荷指示に関する備考',
            'created_at' => 'この出荷指示を作成した日時',
            'updated_at' => 'この出荷指示を最後に更新した日時',
        ],
        'shipment_instruction_lines' => [
            'id' => '出荷指示明細を一意に識別するID',
            'shipment_instruction_id' => '属する出荷指示ヘッダのID',
            'line_no' => '出荷指示明細の行番号',
            'sales_order_id' => '元になった受注ヘッダのID',
            'sales_order_line_id' => '元になった受注明細のID',
            'product_id' => '出荷を指示する商品のID',
            'quantity' => '出荷を指示した数量',
            'picked_quantity' => 'すでに品出し済みの数量',
            'unit_id' => '指示数量の単位ID',
            'note' => '出荷指示明細に関する備考',
            'created_at' => 'この出荷指示明細を作成した日時',
            'updated_at' => 'この出荷指示明細を最後に更新した日時',
        ],
        'shipment_picks' => [
            'id' => '品出ヘッダを一意に識別するID',
            'pick_number' => '品出を一意に識別する番号',
            'status' => '品出の現在の進行状態',
            'shipment_instruction_id' => '元となる出荷指示ヘッダのID',
            'pick_date' => '品出作業を行った日付',
            'stock_location_id' => '品出に使った在庫場所のID',
            'cancelled_reason' => '品出を取り消した理由',
            'cancelled_at' => '品出を取り消した日時',
            'note' => '品出に関する備考',
            'created_at' => 'この品出を作成した日時',
            'updated_at' => 'この品出を最後に更新した日時',
        ],
        'shipment_pick_lines' => [
            'id' => '品出明細を一意に識別するID',
            'shipment_pick_id' => '属する品出ヘッダのID',
            'line_no' => '品出明細の行番号',
            'shipment_instruction_line_id' => '元となる出荷指示明細のID',
            'product_id' => '品出した商品のID',
            'quantity' => '品出した数量',
            'unit_id' => '品出数量の単位ID',
            'note' => '品出明細に関する備考',
            'created_at' => 'この品出明細を作成した日時',
            'updated_at' => 'この品出明細を最後に更新した日時',
        ],
        'shipment_headers' => [
            'id' => '出荷伝票ヘッダを一意に識別するID',
            'document_number' => '出荷伝票を一意に識別する伝票番号',
            'status' => '出荷伝票の現在の進行状態',
            'customer_id' => '出荷先となる取引先のID',
            'transaction_category_id' => '出荷に適用する取引区分のID',
            'settlement_receivable_category_id' => '出荷に適用する売掛・精算区分のID',
            'billing_cycle_id' => '出荷に適用する請求サイクルのID',
            'document_date' => '伝票日付',
            'order_date' => '元受注の日付',
            'scheduled_shipment_date' => '予定していた出荷日',
            'actual_shipment_date' => '実際に出荷した日',
            'sales_recorded_on' => '売上計上日',
            'billing_target_date' => '請求対象日',
            'liquor_tax_transfer_date' => '酒税上の移出日',
            'source_shipment_header_id' => '訂正元となる出荷伝票のID',
            'source_shipment_pick_id' => '元になった品出ヘッダのID',
            'correction_reason' => '訂正出荷を作成した理由',
            'cancelled_at' => '出荷伝票を取り消した日時',
            'cancelled_reason' => '出荷伝票を取り消した理由',
            'note' => '出荷伝票に関する備考',
            'created_at' => 'この出荷伝票を作成した日時',
            'updated_at' => 'この出荷伝票を最後に更新した日時',
        ],
        'shipment_lines' => [
            'id' => '出荷伝票明細を一意に識別するID',
            'shipment_header_id' => '属する出荷伝票ヘッダのID',
            'line_no' => '出荷伝票明細の行番号',
            'product_id' => '出荷した商品のID',
            'quantity' => '出荷数量',
            'unit_id' => '出荷数量の単位ID',
            'source_shipment_pick_line_id' => '元になった品出明細のID',
            'draft_unit_price' => '出荷ドラフト時点での仮単価',
            'draft_price_list_id' => '仮単価算出に使った価格表ID',
            'draft_price_rule_id' => '仮単価算出に使った価格ルールID',
            'draft_price_source' => '仮単価の決定元を表す種別',
            'draft_price_reason' => '仮単価になった理由や補足',
            'draft_priced_at' => '仮単価を計算・設定した日時',
            'confirmed_product_code' => '確定時点で保存した商品コード',
            'confirmed_product_name' => '確定時点で保存した商品名',
            'confirmed_display_name' => '確定時点で帳票表示に使う商品名',
            'confirmed_product_type' => '確定時点で保存した商品種別',
            'confirmed_unit_code' => '確定時点で保存した単位コード',
            'confirmed_unit_name' => '確定時点で保存した単位名',
            'confirmed_quantity' => '確定時点で保存した数量',
            'confirmed_unit_price' => '確定時点で保存した単価',
            'confirmed_price_list_id' => '確定単価の根拠となった価格表ID',
            'confirmed_price_rule_id' => '確定単価の根拠となった価格ルールID',
            'confirmed_price_source' => '確定単価の決定元を表す種別',
            'confirmed_price_reason' => '確定単価になった理由や補足',
            'confirmed_capacity_value' => '確定時点で保存した容量値',
            'confirmed_capacity_unit_id' => '確定時点で保存した容量単位ID',
            'confirmed_alcohol_percentage' => '確定時点で保存したアルコール度数',
            'confirmed_rounding_method' => '確定計算に使った丸め方法',
            'confirmed_consumption_tax_category_id' => '確定時点で保存した消費税区分ID',
            'confirmed_consumption_tax_category_code' => '確定時点で保存した消費税区分コード',
            'confirmed_consumption_tax_category_name' => '確定時点で保存した消費税区分名',
            'confirmed_consumption_taxability' => '確定時点で保存した消費税の課税区分',
            'confirmed_consumption_tax_rate_id' => '確定時点で保存した消費税率ID',
            'confirmed_consumption_tax_rate' => '確定時点で保存した消費税率',
            'confirmed_consumption_tax_rate_effective_from' => '確定時点で保存した消費税率の適用開始日',
            'confirmed_liquor_tax_category_id' => '確定時点で保存した酒税区分ID',
            'confirmed_liquor_tax_category_code' => '確定時点で保存した酒税区分コード',
            'confirmed_liquor_tax_category_name' => '確定時点で保存した酒税区分名',
            'confirmed_liquor_taxability' => '確定時点で保存した酒税の課税区分',
            'confirmed_liquor_tax_rule_id' => '確定時点で保存した酒税ルールID',
            'confirmed_liquor_tax_calculation_method' => '確定時点で保存した酒税計算方法',
            'confirmed_liquor_taxable_kl' => '確定時点で保存した課税数量キロリットル',
            'confirmed_liquor_tax_per_kl' => '確定時点で保存したキロリットル当たり酒税額',
            'confirmed_liquor_tax_reduction_rate' => '確定時点で保存した酒税軽減率',
            'confirmed_liquor_tax_estimated_amount' => '確定時点で保存した酒税見込額',
            'confirmed_at' => 'この明細を確定した日時',
            'note' => '出荷伝票明細に関する備考',
            'created_at' => 'この出荷伝票明細を作成した日時',
            'updated_at' => 'この出荷伝票明細を最後に更新した日時',
        ],
        'stock_locations' => [
            'id' => '在庫場所レコードを一意に識別するID',
            'code' => '在庫場所を識別するコード',
            'name' => '在庫場所名',
            'location_type' => '倉庫・棚などの場所種別',
            'parent_stock_location_id' => '親となる在庫場所のID',
            'is_default_shipping_location' => '標準出荷場所として使うかどうか',
            'is_default_receiving_location' => '標準入荷場所として使うかどうか',
            'is_inventory_managed' => '在庫管理対象の場所かどうか',
            'is_shippable' => '出荷元として利用できる場所かどうか',
            'is_sellable' => '販売可能在庫として扱う場所かどうか',
            'is_tax_relevant' => '税務集計の対象在庫場所かどうか',
            'postal_code' => '在庫場所住所の郵便番号',
            'address1' => '在庫場所住所の1行目',
            'address2' => '在庫場所住所の2行目',
            'phone' => '在庫場所の連絡先電話番号',
            'sort_order' => '画面や帳票での表示順',
            'description' => '在庫場所の補足説明',
            'is_active' => '現在この在庫場所を有効として扱うかどうか',
            'disabled_at' => '在庫場所を無効化した日時',
            'created_at' => 'この在庫場所を作成した日時',
            'updated_at' => 'この在庫場所を最後に更新した日時',
        ],
        'stock_movements' => [
            'id' => '在庫移動レコードを一意に識別するID',
            'status' => '在庫移動の現在の状態',
            'movement_type' => '入庫・出庫・調整などの移動種別',
            'movement_date' => '在庫が動いた業務日付',
            'product_id' => '対象商品のID',
            'stock_location_id' => '在庫が動いた場所のID',
            'unit_id' => '移動数量の単位ID',
            'quantity' => '実際に移動した数量',
            'source_type' => '元になった伝票や処理の種別',
            'source_document_number' => '元伝票番号',
            'source_line_no' => '元伝票の明細番号',
            'source_shipment_header_id' => '元になった出荷伝票ヘッダID',
            'source_shipment_line_id' => '元になった出荷伝票明細ID',
            'related_stock_movement_id' => '取消や訂正で関連する在庫移動のID',
            'production_lot_id' => '紐づく製造ロットのID',
            'lot_code' => '互換表示用や補助参照用のロットコード',
            'confirmed_at' => '在庫移動を確定した日時',
            'closed_at' => '月次締めで締めた日時',
            'cancelled_at' => '在庫移動を取り消した日時',
            'cancelled_reason' => '在庫移動を取り消した理由',
            'reason' => '在庫移動を作成した理由',
            'note' => '在庫移動に関する備考',
            'created_at' => 'この在庫移動を作成した日時',
            'updated_at' => 'この在庫移動を最後に更新した日時',
        ],
        'stock_monthly_balances' => [
            'id' => '月次在庫残高レコードを一意に識別するID',
            'status' => '月次在庫残高の現在の状態',
            'year' => '対象年',
            'month' => '対象月',
            'period_start' => '集計対象期間の開始日',
            'period_end' => '集計対象期間の終了日',
            'product_id' => '対象商品のID',
            'stock_location_id' => '対象在庫場所のID',
            'unit_id' => '残高数量の単位ID',
            'opening_quantity' => '期間開始時点の在庫数量',
            'inbound_quantity' => '期間中の入庫数量合計',
            'outbound_quantity' => '期間中の出庫数量合計',
            'adjustment_quantity' => '期間中の調整数量合計',
            'closing_quantity' => '期間終了時点の在庫数量',
            'calculated_at' => '集計値を計算した日時',
            'confirmed_at' => '月次残高を確定した日時',
            'closed_at' => '月次残高を締めた日時',
            'reason' => 'この集計を作成した理由',
            'note' => '月次残高に関する備考',
            'created_at' => 'この月次残高を作成した日時',
            'updated_at' => 'この月次残高を最後に更新した日時',
        ],
        'invoice_headers' => [
            'id' => '請求ヘッダを一意に識別するID',
            'invoice_number' => '請求書を一意に識別する番号',
            'status' => '請求の現在の進行状態',
            'customer_id' => '請求先となる取引先のID',
            'billing_cycle_id' => '請求に適用する請求サイクルのID',
            'invoice_date' => '請求書を発行した日付',
            'billing_period_start' => '請求対象期間の開始日',
            'billing_period_end' => '請求対象期間の終了日',
            'due_date' => '支払期日',
            'tax_calculation_unit' => '消費税を明細単位か伝票単位かで計算した設定',
            'tax_rounding_method' => '消費税計算時の端数処理方法',
            'amount_rounding_method' => '金額計算時の端数処理方法',
            'subtotal_amount' => '税抜金額の合計',
            'tax_amount' => '消費税額の合計',
            'total_amount' => '税込請求金額の合計',
            'confirmed_at' => '請求を確定した日時',
            'cancelled_at' => '請求を取り消した日時',
            'cancelled_reason' => '請求を取り消した理由',
            'note' => '請求に関する備考',
            'created_at' => 'この請求ヘッダを作成した日時',
            'updated_at' => 'この請求ヘッダを最後に更新した日時',
        ],
        'invoice_lines' => [
            'id' => '請求明細を一意に識別するID',
            'invoice_header_id' => '属する請求ヘッダのID',
            'shipment_header_id' => '元になった出荷伝票ヘッダのID',
            'shipment_line_id' => '元になった出荷伝票明細のID',
            'line_no' => '請求明細の行番号',
            'product_id' => '請求対象商品のID',
            'product_code' => '請求確定時点で保存した商品コード',
            'product_name' => '請求確定時点で保存した商品名',
            'display_name' => '請求書に表示する商品名',
            'quantity' => '請求数量',
            'unit_code' => '請求時点で保存した単位コード',
            'unit_name' => '請求時点で保存した単位名',
            'unit_price' => '請求単価',
            'amount' => '税抜金額',
            'consumption_tax_category_id' => '請求時点で保存した消費税区分ID',
            'consumption_tax_category_code' => '請求時点で保存した消費税区分コード',
            'consumption_tax_category_name' => '請求時点で保存した消費税区分名',
            'consumption_taxability' => '請求時点で保存した消費税の課税区分',
            'consumption_tax_rate_id' => '請求時点で保存した消費税率ID',
            'tax_rate' => '請求時点で適用した消費税率',
            'consumption_tax_rate_effective_from' => '請求時点で参照した税率の適用開始日',
            'tax_amount' => 'この明細の消費税額',
            'total_amount' => 'この明細の税込金額',
            'note' => '請求明細に関する備考',
            'created_at' => 'この請求明細を作成した日時',
            'updated_at' => 'この請求明細を最後に更新した日時',
        ],
        'payment_schedules' => [
            'id' => '入金予定レコードを一意に識別するID',
            'invoice_header_id' => '元になった請求ヘッダのID',
            'customer_id' => '入金予定先の取引先ID',
            'status' => '入金予定の回収状態',
            'expected_payment_date' => '入金予定日',
            'scheduled_amount' => '入金予定額',
            'received_amount' => '現在までに入金済みの金額',
            'outstanding_amount' => 'まだ回収できていない残額',
            'closed_at' => 'この入金予定が回収完了になった日時',
            'note' => '入金予定に関する備考',
            'created_at' => 'この入金予定を作成した日時',
            'updated_at' => 'この入金予定を最後に更新した日時',
        ],
        'payments' => [
            'id' => '入金レコードを一意に識別するID',
            'customer_id' => '入金元の取引先ID',
            'status' => '入金の割当状態',
            'payment_date' => '実際の入金日',
            'payment_method' => '振込などの入金方法',
            'amount' => '入金総額',
            'reference_number' => '振込番号などの参照番号',
            'note' => '入金に関する備考',
            'cancelled_at' => '入金記録を取り消した日時',
            'cancelled_reason' => '入金記録を取り消した理由',
            'created_at' => 'この入金レコードを作成した日時',
            'updated_at' => 'この入金レコードを最後に更新した日時',
        ],
        'payment_allocations' => [
            'id' => '入金充当レコードを一意に識別するID',
            'payment_id' => '充当元となる入金レコードのID',
            'payment_schedule_id' => '充当先となる入金予定レコードのID',
            'invoice_header_id' => '充当対象の請求ヘッダID',
            'allocated_amount' => 'この入金から充当した金額',
            'note' => '入金充当に関する備考',
            'created_at' => 'この入金充当を作成した日時',
            'updated_at' => 'この入金充当を最後に更新した日時',
        ],
        'report_exports' => [
            'id' => '帳票出力レコードを一意に識別するID',
            'report_type' => '出力した帳票の種別',
            'format' => 'PDFやExcelなどの出力形式',
            'status' => '帳票出力の状態',
            'exportable_type' => 'この帳票が紐づく対象モデルの型名',
            'exportable_id' => 'この帳票が紐づく対象レコードのID',
            'disk' => 'ファイルを保存したストレージディスク名',
            'file_path' => '保存先のファイルパス',
            'file_name' => '出力したファイル名',
            'mime_type' => '出力ファイルのMIMEタイプ',
            'file_size' => '出力ファイルのサイズ',
            'checksum_sha256' => 'ファイル内容確認用のSHA256ハッシュ',
            'generated_at' => '帳票ファイルを生成した日時',
            'reason' => '帳票を出力した理由',
            'created_at' => 'この帳票出力履歴を作成した日時',
            'updated_at' => 'この帳票出力履歴を最後に更新した日時',
        ],
        'consumption_tax_monthly_filings' => [
            'id' => '月次消費税集計ヘッダを一意に識別するID',
            'status' => '月次消費税集計の現在の状態',
            'year' => '集計対象の年',
            'month' => '集計対象の月',
            'period_start' => '集計対象期間の開始日',
            'period_end' => '集計対象期間の終了日',
            'total_taxable_amount' => '課税売上額の合計',
            'total_tax_amount' => '消費税額の合計',
            'total_confirmed_tax_amount' => '確定後の消費税額合計',
            'total_amount' => '税込売上額の合計',
            'invoice_count' => '集計対象となった請求件数',
            'line_count' => '集計対象となった請求明細件数',
            'calculated_at' => '集計値を計算した日時',
            'confirmed_at' => '月次消費税集計を確定した日時',
            'closed_at' => '月次消費税集計を締めた日時',
            'reason' => 'この集計を作成した理由',
            'note' => '月次消費税集計に関する備考',
            'created_at' => 'この集計ヘッダを作成した日時',
            'updated_at' => 'この集計ヘッダを最後に更新した日時',
        ],
        'consumption_tax_monthly_filing_lines' => [
            'id' => '月次消費税集計明細を一意に識別するID',
            'consumption_tax_monthly_filing_id' => '属する月次消費税集計ヘッダのID',
            'line_no' => '明細行番号',
            'consumption_tax_category_id' => '集計対象の消費税区分ID',
            'consumption_tax_category_code' => '集計対象の消費税区分コード',
            'consumption_tax_category_name' => '集計対象の消費税区分名',
            'consumption_taxability' => '集計対象の消費税課税区分',
            'consumption_tax_rate_id' => '集計対象の消費税率ID',
            'tax_rate' => '集計対象の消費税率',
            'consumption_tax_rate_effective_from' => '集計対象税率の適用開始日',
            'taxable_amount' => 'この税区分・税率での課税売上額',
            'tax_amount' => 'この税区分・税率での消費税額',
            'confirmed_tax_amount' => '確定後の消費税額',
            'total_amount' => '税込売上額',
            'invoice_count' => '対象請求件数',
            'line_count' => '対象請求明細件数',
            'created_at' => 'この集計明細を作成した日時',
            'updated_at' => 'この集計明細を最後に更新した日時',
        ],
        'liquor_tax_monthly_filings' => [
            'id' => '月次酒税申告ヘッダを一意に識別するID',
            'status' => '月次酒税申告の現在の状態',
            'year' => '集計対象の年',
            'month' => '集計対象の月',
            'period_start' => '集計対象期間の開始日',
            'period_end' => '集計対象期間の終了日',
            'total_taxable_kl' => '課税数量キロリットルの合計',
            'total_estimated_amount' => '酒税見込額の合計',
            'total_confirmed_amount' => '酒税確定額の合計',
            'shipment_count' => '集計対象となった出荷件数',
            'line_count' => '集計対象となった出荷明細件数',
            'calculated_at' => '集計値を計算した日時',
            'confirmed_at' => '月次酒税申告を確定した日時',
            'closed_at' => '月次酒税申告を締めた日時',
            'reason' => 'この集計を作成した理由',
            'note' => '月次酒税申告に関する備考',
            'created_at' => 'この申告ヘッダを作成した日時',
            'updated_at' => 'この申告ヘッダを最後に更新した日時',
        ],
        'liquor_tax_monthly_filing_lines' => [
            'id' => '月次酒税申告明細を一意に識別するID',
            'liquor_tax_monthly_filing_id' => '属する月次酒税申告ヘッダのID',
            'line_no' => '明細行番号',
            'liquor_tax_category_id' => '集計対象の酒税区分ID',
            'liquor_tax_category_code' => '集計対象の酒税区分コード',
            'liquor_tax_category_name' => '集計対象の酒税区分名',
            'liquor_taxability' => '集計対象の酒税課税区分',
            'liquor_tax_rule_id' => '集計対象の酒税ルールID',
            'calculation_method' => 'この明細で使った酒税計算方法',
            'tax_per_kl' => 'この明細で使ったキロリットル当たり酒税額',
            'reduction_rate' => 'この明細で使った軽減率',
            'taxable_kl' => 'この明細での課税数量キロリットル',
            'estimated_amount' => 'この明細での酒税見込額',
            'confirmed_amount' => 'この明細での酒税確定額',
            'shipment_count' => '対象出荷件数',
            'line_count' => '対象出荷明細件数',
            'created_at' => 'この申告明細を作成した日時',
            'updated_at' => 'この申告明細を最後に更新した日時',
        ],
        'receivable_monthly_balances' => [
            'id' => '月次売掛残高レコードを一意に識別するID',
            'status' => '月次売掛残高の現在の状態',
            'year' => '集計対象の年',
            'month' => '集計対象の月',
            'period_start' => '集計対象期間の開始日',
            'period_end' => '集計対象期間の終了日',
            'customer_id' => '対象取引先のID',
            'customer_code' => '集計時点で保存した取引先コード',
            'customer_name' => '集計時点で保存した取引先名',
            'scheduled_amount' => '請求予定額の合計',
            'received_amount' => '入金済額の合計',
            'outstanding_amount' => '未収残高',
            'open_schedule_count' => '未回収の入金予定件数',
            'partial_schedule_count' => '一部回収済みの入金予定件数',
            'closed_schedule_count' => '回収完了した入金予定件数',
            'calculated_at' => '集計値を計算した日時',
            'confirmed_at' => '月次売掛残高を確定した日時',
            'closed_at' => '月次売掛残高を締めた日時',
            'reason' => 'この集計を作成した理由',
            'note' => '月次売掛残高に関する備考',
            'created_at' => 'この月次売掛残高を作成した日時',
            'updated_at' => 'この月次売掛残高を最後に更新した日時',
        ],
        'production_lots' => [
            'id' => '製造ロットレコードを一意に識別するID',
            'lot_code' => '製造ロットを識別するコード',
            'display_name' => '画面や帳票に表示するロット名',
            'status' => '製造ロットの現在の状態',
            'product_id' => '主に紐づく商品のID',
            'stock_location_id' => '主な保管先在庫場所のID',
            'production_date' => '製造日',
            'bottling_date' => '瓶詰日',
            'best_before_date' => '賞味期限または使用期限',
            'tank_code' => '仕込みや貯蔵に使うタンクコード',
            'rice_variety' => '酒米品種',
            'rice_polishing_ratio' => '精米歩合',
            'production_method' => '製法や製造方式',
            'storage_condition' => '保管条件',
            'external_system_code' => '外部システム連携用コード',
            'legacy_lot_text' => '旧システムで使っていたロット表記',
            'search_key' => '検索しやすくするための補助キー',
            'note' => '製造ロットに関する備考',
            'is_active' => '現在この製造ロットを有効として扱うかどうか',
            'disabled_at' => '製造ロットを無効化した日時',
            'created_at' => 'この製造ロットを作成した日時',
            'updated_at' => 'この製造ロットを最後に更新した日時',
        ],
        'product_production_lot' => [
            'id' => '商品ロット候補紐付レコードを一意に識別するID',
            'product_id' => '候補ロットを紐付ける商品のID',
            'production_lot_id' => '候補となる製造ロットのID',
            'usage_type' => 'この紐付の用途区分',
            'priority' => '候補の優先順位',
            'effective_from' => 'この候補設定の適用開始日',
            'effective_until' => 'この候補設定の適用終了日',
            'is_default' => '標準候補として扱うかどうか',
            'is_active' => '現在この候補設定を有効として扱うかどうか',
            'reason' => 'この候補設定を作った理由',
            'note' => '候補設定に関する備考',
            'created_at' => 'この候補設定を作成した日時',
            'updated_at' => 'この候補設定を最後に更新した日時',
        ],
        'shipment_lot_allocations' => [
            'id' => '出荷ロット引当レコードを一意に識別するID',
            'status' => 'ロット引当の現在の状態',
            'shipment_header_id' => '対象となる出荷伝票ヘッダのID',
            'shipment_line_id' => '対象となる出荷伝票明細のID',
            'product_id' => '引当対象商品のID',
            'production_lot_id' => '引当てた製造ロットのID',
            'stock_location_id' => '引当元在庫場所のID',
            'unit_id' => '引当数量の単位ID',
            'quantity' => '引当てた数量',
            'allocated_at' => 'ロットを引当てた日時',
            'confirmed_at' => '出荷確定に伴い引当を確定した日時',
            'cancelled_at' => '引当を取り消した日時',
            'cancelled_reason' => '引当を取り消した理由',
            'reason' => 'この引当を作成した理由',
            'note' => '引当に関する備考',
            'created_at' => 'この引当レコードを作成した日時',
            'updated_at' => 'この引当レコードを最後に更新した日時',
        ],
        'shipment_stock_reservations' => [
            'id' => '出荷在庫予約レコードを一意に識別するID',
            'status' => '在庫予約の現在の状態',
            'shipment_header_id' => '対象となる出荷伝票ヘッダのID',
            'shipment_line_id' => '対象となる出荷伝票明細のID',
            'product_id' => '予約対象商品のID',
            'stock_location_id' => '予約元在庫場所のID',
            'unit_id' => '予約数量の単位ID',
            'quantity' => '予約した数量',
            'reserved_at' => '在庫を予約した日時',
            'confirmed_at' => '出荷確定に伴い予約を確定した日時',
            'released_at' => '予約を解放した日時',
            'cancelled_at' => '予約を取り消した日時',
            'cancelled_reason' => '予約を取り消した理由',
            'reason' => 'この予約を作成した理由',
            'note' => '在庫予約に関する備考',
            'created_at' => 'この予約レコードを作成した日時',
            'updated_at' => 'この予約レコードを最後に更新した日時',
        ],
        'failed_jobs' => [
            'id' => '失敗ジョブレコードを一意に識別するID',
            'uuid' => '失敗したジョブのUUID',
            'connection' => 'ジョブを処理したキュー接続名',
            'queue' => 'ジョブが投入されていたキュー名',
            'payload' => '失敗したジョブの実行データ',
            'exception' => '失敗時の例外内容',
            'failed_at' => 'ジョブが失敗として記録された日時',
        ],
        'operation_jobs' => [
            'id' => '運用ジョブレコードを一意に識別するID',
            'job_type' => '運用ジョブの種別',
            'status' => '運用ジョブの現在の状態',
            'target_type' => '処理対象モデルの型名',
            'target_id' => '処理対象レコードの識別子',
            'idempotency_key' => '重複実行防止のための冪等キー',
            'payload' => 'ジョブ実行に必要な入力データ',
            'attempts' => '実行または再実行した回数',
            'retry_of_operation_job_id' => '再実行元となる運用ジョブID',
            'started_at' => 'ジョブ処理を開始した日時',
            'finished_at' => 'ジョブ処理を正常終了した日時',
            'failed_at' => 'ジョブ処理が失敗した日時',
            'cancelled_at' => 'ジョブ処理を取り消した日時',
            'error_message' => '失敗時に保存するエラーメッセージ',
            'reason' => 'このジョブを起動した理由',
            'created_at' => 'この運用ジョブを作成した日時',
            'updated_at' => 'この運用ジョブを最後に更新した日時',
        ],
        'approval_requests' => [
            'id' => '承認依頼レコードを一意に識別するID',
            'approval_number' => '承認依頼を一意に識別する番号',
            'status' => '承認依頼の現在の状態',
            'action_type' => '承認対象となる操作の種別',
            'target_type' => '承認対象モデルの型名',
            'target_id' => '承認対象レコードの識別子',
            'requested_by_user_id' => '承認を申請したユーザーのID',
            'approved_by_user_id' => '最終的に承認したユーザーのID',
            'requested_at' => '承認を申請した日時',
            'approved_at' => '承認された日時',
            'rejected_at' => '却下された日時',
            'returned_at' => '差し戻された日時',
            'consumed_at' => '承認結果が実処理に使われた日時',
            'payload' => '承認対象の入力データや差分内容',
            'reason' => '承認を申請した理由',
            'approver_comment' => '承認者が残したコメント',
            'return_reason' => '差し戻し理由',
            'created_at' => 'この承認依頼を作成した日時',
            'updated_at' => 'この承認依頼を最後に更新した日時',
        ],
        'approval_request_actions' => [
            'id' => '承認操作履歴レコードを一意に識別するID',
            'approval_request_id' => '対象となる承認依頼のID',
            'action' => 'approve や reject など実行した操作種別',
            'from_status' => '操作前の承認依頼ステータス',
            'to_status' => '操作後の承認依頼ステータス',
            'user_id' => 'この操作を実行したユーザーのID',
            'comment' => '操作時に残したコメント',
            'acted_at' => '操作を実行した日時',
            'created_at' => 'この承認操作履歴を作成した日時',
            'updated_at' => 'この承認操作履歴を最後に更新した日時',
        ],
    ];

    public function up(): void
    {
        foreach ($this->columnComments as $table => $columns) {
            if (! Schema::hasTable($table)) {
                continue;
            }

            foreach ($columns as $column => $comment) {
                if (! Schema::hasColumn($table, $column)) {
                    continue;
                }

                $this->commentColumn($table, $column, $comment);
            }
        }
    }

    public function down(): void
    {
        foreach ($this->columnComments as $table => $columns) {
            if (! Schema::hasTable($table)) {
                continue;
            }

            foreach (array_keys($columns) as $column) {
                if (! Schema::hasColumn($table, $column)) {
                    continue;
                }

                DB::statement("COMMENT ON COLUMN {$table}.{$column} IS NULL");
            }
        }
    }

    private function commentColumn(string $table, string $column, string $comment): void
    {
        $escapedComment = str_replace("'", "''", $comment);
        DB::statement("COMMENT ON COLUMN {$table}.{$column} IS '{$escapedComment}'");
    }
};
