<?php

return [
    'roles' => [
        'admin' => [
            'name' => '管理者',
            'description' => '全権限を持つ管理者ロール。',
        ],
    ],

    'permissions' => [
        'sales_order.update' => '受注更新',
        'price.change' => '価格変更',
        'tax_rule.change' => '税ルール変更',
        'liquor_tax_rule.change' => '酒税ルール変更',
        'monthly_closing.view' => '月次締め閲覧',
        'monthly_closing.execute' => '締処理',
        'monthly_closing.reopen' => '締解除',
        'search.view' => '検索閲覧',
        'stock.adjust' => '在庫調整',
        'document.cancel' => '伝票取消',
        'payment.allocate' => '入金消込',
        'audit_log.view' => '監査ログ閲覧',
        'approval.view' => '承認依頼閲覧',
        'approval.request' => '承認依頼作成',
        'approval.approve' => '承認処理',
        'report.reissue' => '帳票再発行',
        'role.manage' => '権限変更',
        'customer_master.view' => '取引先マスター閲覧',
        'customer_master.edit' => '取引先マスター編集',
        'billing_cycle_master.view' => '締日条件マスター閲覧',
        'billing_cycle_master.edit' => '締日条件マスター編集',
        'product_master.view' => '商品マスター閲覧',
        'product_master.edit' => '商品マスター編集',
        'sales_order.view' => '受注閲覧',
        'sales_order.create' => '受注作成',
        'sales_order.cancel' => '受注取消',
        'shipment_instruction.view' => '出荷指示閲覧',
        'shipment_instruction.create' => '出荷指示作成',
        'shipment_instruction.cancel' => '出荷指示取消',
        'shipment_pick.view' => '品出閲覧',
        'shipment_pick.create' => '品出作成',
        'shipment_pick.cancel' => '品出取消',
        'shipment.view' => '出荷伝票閲覧',
        'shipment.create' => '出荷伝票作成',
        'shipment.price' => '出荷伝票価格適用',
        'shipment.confirm' => '出荷伝票確定',
        'shipment.cancel' => '出荷伝票取消',
        'inventory.view' => '在庫閲覧',
        'inventory.reserve' => '在庫予約',
        'inventory.allocate' => 'ロット引当',
        'billing.view' => '請求入金閲覧',
        'billing.invoice.create' => '請求ドラフト作成',
        'billing.invoice.confirm' => '請求確定',
        'billing.invoice.cancel' => '請求取消',
        'billing.payment_schedule.create' => '入金予定作成',
        'billing.payment.create' => '入金登録',
        'billing.payment.cancel' => '入金取消',
        'sales_return.view' => '返品閲覧',
        'sales_return.create' => '返品・赤伝作成',
        'non_sales_stock.view' => '販売外在庫出入閲覧',
        'non_sales_stock.create' => '販売外在庫出入作成',
        'tax.view' => '税務閲覧',
        'tax.liquor_filing.create' => '酒税月次申告ドラフト作成',
        'tax.liquor_filing.confirm' => '酒税月次申告確定',
        'tax.liquor_settings.manage' => '酒税計算設定管理',
        'tax.consumption_filing.create' => '消費税月次申告ドラフト作成',
        'tax.consumption_filing.confirm' => '消費税月次申告確定',
    ],
];
