<?php
namespace App\Http\Controllers;
use App\Models\User;
use App\Models\InvoiceHeader;
use App\Models\ShipmentInstruction;
use App\Models\ShipmentHeader;
use App\Models\StockLocation;
use Illuminate\Support\Facades\DB;
use App\Services\Authorization\AuthorizationService;
use Illuminate\Http\Request;
use Illuminate\View\View;
class LogisticsPageController extends Controller {
 public function picks(Request $request, AuthorizationService $auth): View { $user=$request->user(); return view('logistics.picks',['user'=>$user,'canCreate'=>$auth->can($user,'shipment_pick.create'),'canCancel'=>$auth->can($user,'shipment_pick.cancel'),'canApprove'=>$auth->can($user,'approval.approve')]); }
 public function shipments(Request $request, AuthorizationService $auth): View { $user=$request->user(); return view('logistics.shipments',['user'=>$user,'canCreate'=>$auth->can($user,'shipment.create'),'canPrice'=>$auth->can($user,'shipment.price'),'canConfirm'=>$auth->can($user,'shipment.confirm'),'canCancel'=>$auth->can($user,'shipment.cancel')]); }
 public function shipmentHistory(Request $request): View { return view('logistics.shipment-history',['user'=>$request->user()]); }
 public function confirmedShipments(Request $request, AuthorizationService $auth): View { $user=$request->user(); return view('logistics.confirmed-shipments',['user'=>$user,'canCancel'=>$auth->can($user,'shipment.cancel'),'canConfirm'=>$auth->can($user,'shipment.confirm')]); }
 public function workSlip(ShipmentInstruction $shipmentInstruction): View { abort_if($shipmentInstruction->status === 'cancelled', 404); $shipmentInstruction->load(['customer','stockLocation','lines.product','lines.unit','lines.salesOrder']); $lineIds=$shipmentInstruction->lines->pluck('id'); $lotNamesByLine=DB::table('shipment_lot_allocations')->join('shipment_lines','shipment_lines.id','=','shipment_lot_allocations.shipment_line_id')->join('shipment_headers','shipment_headers.id','=','shipment_lines.shipment_header_id')->leftJoin('shipment_pick_lines','shipment_pick_lines.id','=','shipment_lines.source_shipment_pick_line_id')->leftJoin('shipment_instruction_lines as direct_instruction_lines',function($join){$join->on('direct_instruction_lines.shipment_instruction_id','=','shipment_headers.source_shipment_instruction_id')->on('direct_instruction_lines.line_no','=','shipment_lines.line_no');})->leftJoin('production_lots','production_lots.id','=','shipment_lot_allocations.production_lot_id')->where(function($query)use($shipmentInstruction,$lineIds):void{$query->where('shipment_headers.source_shipment_instruction_id',$shipmentInstruction->id)->orWhereIn('shipment_pick_lines.shipment_instruction_line_id',$lineIds);})->where('shipment_headers.status','!=','cancelled')->whereIn('shipment_lot_allocations.status',['allocated','confirmed'])->whereNull('shipment_lot_allocations.cancelled_at')->whereRaw('COALESCE(shipment_pick_lines.shipment_instruction_line_id, direct_instruction_lines.id) IS NOT NULL')->selectRaw('COALESCE(shipment_pick_lines.shipment_instruction_line_id, direct_instruction_lines.id) as instruction_line_id, COALESCE(production_lots.display_name, production_lots.lot_code) as lot_name, shipment_lot_allocations.quantity as quantity')->get()->groupBy('instruction_line_id')->map(fn($rows)=>$rows->map(fn($row)=>trim((string) $row->lot_name).($row->quantity !== null ? ' / '.rtrim(rtrim(number_format((float) $row->quantity, 4, '.', ''), '0'), '.') : ''))->filter()->implode('、')); return view('logistics.work-slip',['instruction'=>$shipmentInstruction,'lotNamesByLine'=>$lotNamesByLine]); }
 public function printShipment(ShipmentHeader $shipment): View { return view('logistics.shipment-print',['shipment'=>$shipment->load(['customer','lines.product.consumptionTaxCategory','lines.unit','lines.lotAllocations.productionLot','sourceShipmentInstruction.lines.salesOrder','sourceShipmentPick.shipmentInstruction.lines.salesOrder'])]); }
 public function billing(Request $request, AuthorizationService $auth): View { $user=$request->user(); $routeName=$request->route()?->getName(); $section=match($routeName){'billing.monthly-invoices'=>'monthly-invoices','billing.spot-invoices'=>'spot-invoices','billing.invoices'=>'invoices','billing.invoice-print'=>'invoice-print','billing.payment-confirmation'=>'payment-confirmation','billing.payment-reviews'=>'payment-reviews','billing.receivables'=>'receivables',default=>'dashboard'}; return view('billing.index',['user'=>$user,'section'=>$section,'canInvoiceCreate'=>$auth->can($user,'billing.invoice.create'),'canInvoiceConfirm'=>$auth->can($user,'billing.invoice.confirm'),'canInvoiceCancel'=>$auth->can($user,'billing.invoice.cancel'),'canPaymentCreate'=>$auth->can($user,'billing.payment.create'),'canPaymentCancel'=>$auth->can($user,'billing.payment.cancel'),'canScheduleCreate'=>$auth->can($user,'billing.payment_schedule.create')]); }
 public function printInvoice(InvoiceHeader $invoice): View { abort_if($invoice->status !== 'confirmed', 404); return view('billing.invoice-print',['invoice'=>$invoice->load(['customer','billingCycle','lines.shipmentHeader'])]); }
 public function printInvoices(Request $request): View { $ids=collect(explode(',', (string) $request->query('ids')))->map(fn($id)=>(int) trim($id))->filter()->unique()->values(); abort_if($ids->isEmpty(), 404); $invoices=InvoiceHeader::query()->with(['customer','billingCycle','lines.shipmentHeader'])->whereIn('id',$ids)->where('status','confirmed')->get()->sortBy(fn($invoice)=>$ids->search($invoice->id))->values(); abort_if($invoices->isEmpty(), 404); return view('billing.invoice-print-batch',['invoices'=>$invoices]); }
 public function salesReturns(Request $request, AuthorizationService $auth): View { $user=$request->user(); $canCreate=$auth->can($user,'sales_return.create'); $routeName=$request->route()?->getName(); $section=match($routeName){'sales-returns.history'=>'history',default=>'register'}; return view('sales-returns.index',['user'=>$user,'section'=>$section,'canCreate'=>$canCreate,'canCancel'=>$canCreate,'stockLocations'=>StockLocation::query()->where('is_active',true)->where('is_inventory_managed',true)->orderBy('sort_order')->orderBy('id')->get()]); }
}
