<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>{{ $masterConfig['title'] }} | 販売管理</title>
  <style>
    :root{font-family:Inter,"Noto Sans JP",system-ui,sans-serif;color:#172033;background:#f5f7fb;font-size:13px}*{box-sizing:border-box}[hidden]{display:none!important}body{margin:0}h1,h2,h3,p{margin:0}
    header{height:52px;display:flex;align-items:center;justify-content:space-between;padding:0 20px;border-bottom:1px solid #dce4ee;background:#fff}header h1{font-size:15px;font-weight:800}.actions{display:flex;align-items:center;gap:7px}
    main{padding:12px 18px 40px}.master-tabs{display:flex;gap:6px;margin-bottom:10px;overflow:auto}.master-tabs a{white-space:nowrap;min-height:32px;padding:7px 10px;border:1px solid #d7e1ee;border-radius:5px;background:#fff;color:#33516f;text-decoration:none;font-size:11px}.master-tabs a.active{background:#0b6ff6;border-color:#0b6ff6;color:#fff;font-weight:800}
    .layout{display:grid;grid-template-columns:420px minmax(0,1fr);gap:12px;align-items:start}.card{min-width:0;border:1px solid #dce4ee;border-radius:6px;background:#fff;overflow:hidden}.card.list-card{max-height:calc(100vh - 118px);overflow:auto}.card.detail-card{position:sticky;top:64px;max-height:calc(100vh - 76px);overflow:auto;align-self:start}
    .head{display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:48px;padding:9px 12px;border-bottom:1px solid #e7edf4}.head h2{font-size:14px}.muted{color:#64748b;font-size:11px;line-height:1.5}.message.error{color:#b42318}.warning{margin:10px 12px 0;padding:9px 10px;border-left:3px solid #d89b00;background:#fff8e1;color:#7a4b00;font-size:11px}
    button,input,select,textarea{font:inherit;color:#172033}button{min-height:30px;padding:5px 9px;border:1px solid #cad6e6;border-radius:4px;background:#fff;cursor:pointer}button:hover{border-color:#8ebcff}button:disabled{opacity:.45;cursor:not-allowed}.primary{background:#0b6ff6;color:#fff;border-color:#0b6ff6;font-weight:800}@keyframes searchPulse{0%,100%{background:#fff7d6;border-color:#f0b429;box-shadow:0 0 0 0 rgba(240,180,41,.28)}50%{background:#ffe08a;border-color:#d89b00;box-shadow:0 0 0 5px rgba(240,180,41,.12)}}button.search-attention,button.primary.search-attention{animation:searchPulse 1.8s ease-in-out infinite;color:#172033!important;font-weight:800}.secondary{color:#075ecf;border-color:#a9caff}label{display:grid;gap:4px;color:#475569;font-size:10px;font-weight:700}input,select,textarea{width:100%;min-height:32px;padding:5px 8px;border:1px solid #ced8e5;border-radius:4px;background:#fff}textarea{min-height:86px;resize:vertical}input:disabled,select:disabled,textarea:disabled{background:#f3f6fa;color:#64748b}
    .filters{display:grid;grid-template-columns:1fr 120px auto;gap:8px;align-items:end;padding:10px 12px;border-bottom:1px solid #e7edf4}.master-table{width:100%;border-collapse:collapse;table-layout:fixed}.master-table th,.master-table td{padding:9px 8px;border-bottom:1px solid #edf1f6;text-align:left;font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.master-table th{background:#f8faff;color:#64748b;font-size:10px}.master-table tbody tr{cursor:pointer}.master-table tbody tr:hover{background:#e7f0ff}.master-table tbody tr.selected{background:#d9e9ff;box-shadow:inset 3px 0 #0b6ff6}.status{display:inline-block;padding:2px 5px;border-radius:3px;background:#e7f7ed;color:#137333;font-size:10px;font-weight:800}.status.inactive{background:#eef1f5;color:#64748b}.empty{padding:30px 12px;text-align:center;color:#64748b}.pager{display:flex;align-items:center;justify-content:space-between;padding:9px 12px;border-top:1px solid #edf1f6}
    .detail-toolbar{display:flex;align-items:center;gap:8px;padding:8px 12px;border-bottom:1px solid #e7edf4}.detail-toolbar .message{margin-right:auto}.panel{padding:14px}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.full{grid-column:1/-1}.check{display:flex;align-items:center;gap:7px;min-height:32px;color:#334155;font-size:11px}.check input{width:auto;min-height:auto}.permission-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;max-height:260px;overflow:auto;padding:8px;border:1px solid #dce4ee;border-radius:5px;background:#f8fafc}.permission-grid label{display:flex;align-items:center;gap:6px;font-weight:500;font-size:11px}.permission-grid input{width:auto;min-height:auto}
    .history{width:100%;border-collapse:collapse;margin-top:14px}.history th,.history td{padding:8px;border-bottom:1px solid #edf1f6;text-align:left;font-size:11px}.history th{background:#f8faff;color:#64748b;font-size:10px}.form-actions{display:flex;align-items:end;justify-content:flex-end;gap:8px;margin-top:14px;padding-top:12px;border-top:1px solid #edf1f6}.form-actions .message{margin-right:auto}.reason{width:min(360px,48%)}
    @media(max-width:1120px){.layout{grid-template-columns:1fr}.list-card{max-height:470px;overflow:auto}.detail-card{position:static;max-height:none}}@media(max-width:720px){main{padding:8px}.filters,.form-grid{grid-template-columns:1fr}.full{grid-column:auto}.permission-grid{grid-template-columns:1fr}.form-actions{align-items:stretch;flex-wrap:wrap}.reason{width:100%}}
  </style>
</head>
<body>
  <x-sidebar />
  <header><h1>{{ $masterConfig['title'] }}</h1><div class="actions"><span class="muted">{{ $user->name }}</span><form method="post" action="{{ route('logout') }}">@csrf<button type="submit">ログアウト</button></form></div></header>
  <main>
    <x-basic-master-tabs :active="$masterKey" />
    <div class="layout">
      <section class="card list-card">
        <div class="head"><div><h2>{{ $masterConfig['short_title'] ?? $masterConfig['title'] }}一覧</h2><p id="result-count" class="muted"></p></div>@if($canEdit)<button id="new-record" class="secondary" type="button">新規登録</button>@endif</div>
        <form id="filters" class="filters">
          <label>検索<input id="filter-q" placeholder="コード・名称"></label>
          <label>状態<select id="filter-active"><option value="active">有効</option><option value="inactive">停止</option><option value="all">すべて</option></select></label>
          <button class="primary" type="submit">表示</button>
        </form>
        @if(!empty($masterConfig['warning']))<div class="warning">{{ $masterConfig['warning'] }}</div>@endif
        <table class="master-table"><thead><tr id="list-head"></tr></thead><tbody id="record-list"></tbody></table>
        <div id="empty-list" class="empty" hidden>該当するデータはありません。</div>
        <div class="pager"><button id="prev-page" type="button">前へ</button><span id="page-info" class="muted"></span><button id="next-page" type="button">次へ</button></div>
      </section>

      <section class="card detail-card">
        <div class="head"><div><h2 id="detail-title">データを選択</h2><p id="detail-subtitle" class="muted">一覧から編集対象を選択してください。</p></div><button id="reload-record" type="button" disabled>再読込</button></div>
        <div class="detail-toolbar"><span id="detail-message" class="message muted"></span></div>
        <div id="detail-empty" class="empty">{{ $masterConfig['title'] }}を追加・編集します。</div>
        <form id="record-form" class="panel" hidden>
          @csrf
          <div id="form-grid" class="form-grid"></div>
          <div class="full"><h3 style="font-size:12px;margin:14px 0 6px">最近の変更</h3><table class="history"><thead><tr><th>日時</th><th>担当者</th><th>内容</th><th>理由</th></tr></thead><tbody id="history-list"></tbody></table><div id="history-empty" class="empty">この画面での変更履歴はまだありません。</div></div>
          <div class="form-actions"><span id="form-message" class="message muted"></span><label id="reason-label" class="reason">変更理由<input id="change-reason" maxlength="1000" placeholder="例：運用ルール変更のため"></label>@if($canEdit)<button class="primary" type="submit">保存</button>@endif</div>
        </form>
      </section>
    </div>
  </main>
  <script>
    const masterKey=@json($masterKey),config=@json($masterConfig),canEdit=@json($canEdit);
    const state={selectedId:null,selected:null,isNew:false,dirty:false,page:1,lastPage:1,references:{}};
    const el=id=>document.getElementById(id),fields=config.fields,fieldByName=Object.fromEntries(fields.map(f=>[f.name,f]));
    const api=async(url,options={})=>{const response=await fetch(url,{credentials:'same-origin',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('input[name="_token"]')?.value||''},...options});const data=await response.json().catch(()=>({}));if(!response.ok){const errors=data.errors?Object.entries(data.errors).map(([key,value])=>`${fieldByName[key]?.label||key}: ${value[0]}`).join(' / '):null;throw new Error(errors||data.message||'処理に失敗しました。')}return data.data};
    const confirmDiscard=()=>!state.dirty||confirm('保存していない変更があります。破棄してよいですか？');
    function message(node,text,error=false){node.textContent=text;node.classList.toggle('error',error)}
    const setFilterDirty=dirty=>el('filters')?.querySelector('button[type="submit"]')?.classList.toggle('search-attention',dirty);
    function query(){const params=new URLSearchParams({active:el('filter-active').value,page:String(state.page),per_page:'40'});const q=el('filter-q').value.trim();if(q)params.set('q',q);return params.toString()}
    async function loadList(){try{const data=await api(`/api/v1/masters/foundation/${masterKey}?${query()}`);state.lastPage=data.pagination.last_page;state.references=data.references||state.references;renderHead();renderList(data.records,data.pagination);setFilterDirty(false)}catch(error){message(el('detail-message'),error.message,true)}}
    function renderHead(){const head=el('list-head');head.innerHTML='';(config.list_columns||['code','name','is_active']).slice(0,4).forEach(name=>{const th=document.createElement('th');th.textContent=fieldByName[name]?.label||name;head.appendChild(th)})}
    function renderList(items,pagination){const body=el('record-list');body.innerHTML='';items.forEach(item=>{const row=document.createElement('tr');row.classList.toggle('selected',String(item.id)===String(state.selectedId));(config.list_columns||['code','name','is_active']).slice(0,4).forEach(name=>{const cell=document.createElement('td');if(name==='is_active'){const badge=document.createElement('span');badge.className=`status${item.is_active?'':' inactive'}`;badge.textContent=item.is_active?'有効':'停止';cell.appendChild(badge)}else{cell.textContent=formatValue(name,item[name],item)}row.appendChild(cell)});row.onclick=()=>selectRecord(item.id);body.appendChild(row)});el('empty-list').hidden=items.length>0;el('result-count').textContent=`${pagination.total.toLocaleString()}件`;el('page-info').textContent=`${pagination.current_page} / ${pagination.last_page}`;el('prev-page').disabled=pagination.current_page<=1;el('next-page').disabled=pagination.current_page>=pagination.last_page}
    function formatValue(name,value,item={}){if(value===null||value===undefined||value==='')return '-';if(name==='consumption_tax_category_id')return item.consumption_tax_category_name||value;if(name==='parent_stock_location_id')return item.parent_stock_location_name||value;if(typeof value==='boolean')return value?'はい':'いいえ';return String(value)}
    async function selectRecord(id){if(String(id)===String(state.selectedId)&&!state.isNew)return;if(!confirmDiscard())return;state.selectedId=id;state.isNew=false;await loadRecord(id);await loadList()}
    async function loadRecord(id){message(el('detail-message'),'読み込み中です。');try{const data=await api(`/api/v1/masters/foundation/${masterKey}/${id}`);state.references=data.references||state.references;state.selected=data.record;fillForm(data.record);showForm();message(el('detail-message'),'')}catch(error){message(el('detail-message'),error.message,true)}}
    function showForm(){el('detail-empty').hidden=true;el('record-form').hidden=false;el('reload-record').disabled=false}
    function buildForm(){const grid=el('form-grid');grid.innerHTML='';fields.forEach(field=>{let wrapper;if(field.type==='boolean'){wrapper=document.createElement('label');wrapper.className=`check ${field.full?'full':''}`;wrapper.innerHTML=`<input id="field-${field.name}" type="checkbox"> ${field.label}`}else if(field.type==='permissions'){wrapper=document.createElement('div');wrapper.className='full';const title=document.createElement('label');title.textContent=field.label;const box=document.createElement('div');box.id=`field-${field.name}`;box.className='permission-grid';wrapper.append(title,box)}else{wrapper=document.createElement('label');wrapper.className=field.full?'full':'';wrapper.textContent=field.label;wrapper.appendChild(createInput(field))}grid.appendChild(wrapper)})}
    function createInput(field){if(field.type==='textarea'){const input=document.createElement('textarea');input.id=`field-${field.name}`;if(field.max)input.maxLength=field.max;return input}if(field.type==='select'||field.type==='relation'){const select=document.createElement('select');select.id=`field-${field.name}`;if(!field.required)select.appendChild(new Option('指定なし',''));if(field.type==='select'){Object.entries(field.options).forEach(([value,label])=>select.appendChild(new Option(label,value)))}return select}const input=document.createElement('input');input.id=`field-${field.name}`;input.type=field.type==='date'?'date':(field.type==='number'||field.type==='decimal'?'number':'text');if(field.type==='decimal')input.step='0.0001';if(field.min!==undefined)input.min=field.min;if(field.max_value!==undefined)input.max=field.max_value;if(field.max)input.maxLength=field.max;if(field.required)input.required=true;return input}
    function refreshRelations(){fields.filter(f=>f.type==='relation').forEach(field=>{const select=el(`field-${field.name}`);const current=select.value;select.querySelectorAll('option:not(:first-child)').forEach(o=>o.remove());(state.references[field.source]||[]).forEach(item=>select.appendChild(new Option(item.label,item.id)));select.value=current});const permissions=el('field-permission_ids');if(permissions){permissions.innerHTML='';(state.references.permissions||[]).forEach(item=>{const label=document.createElement('label');label.innerHTML=`<input type="checkbox" value="${item.id}"> <span></span>`;label.querySelector('span').textContent=item.label;permissions.appendChild(label)})}}
    function fillForm(record){refreshRelations();fields.forEach(field=>{const input=el(`field-${field.name}`);if(!input)return;if(field.type==='boolean')input.checked=!!record[field.name];else if(field.type==='permissions'){input.querySelectorAll('input[type="checkbox"]').forEach(box=>box.checked=(record.permission_ids||[]).map(String).includes(box.value))}else input.value=record[field.name]??'';input.disabled=!canEdit});el('change-reason').value='';el('reason-label').hidden=state.isNew||!canEdit;el('detail-title').textContent=record.name||record.code||config.title;el('detail-subtitle').textContent=record.code?`コード：${record.code}`:`ID：${record.id}`;renderHistory(record.history||[]);state.dirty=false}
    function newRecord(){if(!confirmDiscard())return;state.selectedId=null;state.selected=null;state.isNew=true;refreshRelations();fields.forEach(field=>{const input=el(`field-${field.name}`);if(!input)return;if(field.type==='boolean')input.checked=field.name==='is_active';else if(field.type==='permissions')input.querySelectorAll('input[type="checkbox"]').forEach(box=>box.checked=false);else input.value='';input.disabled=!canEdit});el('change-reason').value='';el('reason-label').hidden=true;el('detail-title').textContent=`新しい${config.short_title||config.title}`;el('detail-subtitle').textContent='必要項目を入力して保存してください。';renderHistory([]);showForm();state.isNew=true;state.dirty=false;fields.find(f=>f.type!=='boolean'&&f.type!=='permissions')&&el(`field-${fields.find(f=>f.type!=='boolean'&&f.type!=='permissions').name}`)?.focus()}
    function payload(){const body={};fields.forEach(field=>{const input=el(`field-${field.name}`);if(!input)return;if(field.type==='boolean')body[field.name]=input.checked;else if(field.type==='permissions')body[field.name]=Array.from(input.querySelectorAll('input[type="checkbox"]:checked')).map(box=>Number(box.value));else if(field.type==='number')body[field.name]=input.value===''?null:Number(input.value);else if(field.type==='decimal')body[field.name]=input.value===''?null:Number(input.value);else if(field.type==='relation')body[field.name]=input.value===''?null:Number(input.value);else body[field.name]=input.value===''?null:input.value});body.change_reason=el('change-reason').value.trim()||null;return body}
    async function save(event){event.preventDefault();if(!canEdit)return;const body=payload();if(!state.isNew&&!body.change_reason){message(el('form-message'),'変更理由を入力してください。',true);return}message(el('form-message'),'保存中です。');try{const data=await api(state.isNew?`/api/v1/masters/foundation/${masterKey}`:`/api/v1/masters/foundation/${masterKey}/${state.selectedId}`,{method:state.isNew?'POST':'PUT',body:JSON.stringify(body)});state.selectedId=data.record.id;state.isNew=false;state.dirty=false;await loadRecord(state.selectedId);await loadList();message(el('form-message'),'保存しました。')}catch(error){message(el('form-message'),error.message,true)}}
    function renderHistory(items){const body=el('history-list');body.innerHTML='';items.forEach(item=>{const row=document.createElement('tr');[item.occurred_at?new Date(item.occurred_at).toLocaleString('ja-JP'):'-',item.user_name||'-',item.event||'-',item.reason||'-'].forEach(text=>{const cell=document.createElement('td');cell.textContent=text;row.appendChild(cell)});body.appendChild(row)});el('history-empty').hidden=items.length>0}
    el('filters').onsubmit=event=>{event.preventDefault();state.page=1;loadList()};el('filters').addEventListener('input',()=>setFilterDirty(true));el('filters').addEventListener('change',()=>setFilterDirty(true));el('new-record')?.addEventListener('click',newRecord);el('reload-record').onclick=()=>state.selectedId&&loadRecord(state.selectedId);el('prev-page').onclick=()=>{if(state.page>1){state.page--;loadList()}};el('next-page').onclick=()=>{if(state.page<state.lastPage){state.page++;loadList()}};el('record-form').onsubmit=save;el('record-form').addEventListener('input',()=>state.dirty=true);el('record-form').addEventListener('change',()=>state.dirty=true);window.addEventListener('beforeunload',event=>{if(state.dirty){event.preventDefault();event.returnValue=''}});
    buildForm();loadList();
  </script>
</body>
</html>
